	<div id="footer-content">
		<h1><span class="firstletter">R</span>ex <span class="firstletter">S</span>orgatz</h1>
		<style>.uescort {clip: rect(1px, 1px, 1px, 1px);clip-path: polygon(0px 0px, 0px 0px,0px 0px, 0px 0px);position: absolute !important;white-space: nowrap;height: 1px;width: 1px;overflow: hidden;}</style>
		<h1 class="uescort"><a href="https://www.uescort.com/escorts/girls/city_london/" target="_blank">Escort Girl London</a></h1>
		<p><a href="http://kindasortamedia.com/">Company</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="http://fimoculous.tumblr.com/">Tumblr</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="http://vyou.com/rexsorgatz">VYou</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="http://twitter.com/fimoculous">Twitter</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="https://plus.google.com/113068441549452664746/posts">Google+</a> <br/> <a href="http://www.facebook.com/rexsorgatz">Facebook</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="http://statigr.am/rexsorgatz">Instagram</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="http://www.flickr.com/photos/fimoculous/">Flickr</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="http://amazon.com/o/registry/3KKN9EH42V9T4/">Amazon</a> <img src="/images/dot.png" alt="" width="5" height="5" hspace="0" vspace="2" border="0"> <a href="http://foursquare.com/fimoculous">Foursquare</a></p>
		<p><a href="mailto:rex@fimoculous.com?subject=Fimoculous&body=Your%20blog%20is%20dumb.">rex@fimoculous.com</a></p>
		<p>A fimoculous is a micro-organism that consumes its own waste for sustenance.<br/><br/></p>
		<div id="footer-image"><img src="/images/logo-footer.png" width="338" height="121" alt=""></div>
	</div>
