<cfset chapter = "Shin"><cfinclude template="../_header.cfm">

<article>

	<h1><a href="/">The Arabic Alphabet: A Guided Tour</a></h1>
	<h4>by Michael Beard</h4>
	<h5>illustrated by Houman Mortazavi</h5>
		
	<div class="illo"><img src="../_img/shin1.png" alt="Shin" /></div>
	<h2>Shin is for Saracen</h2>
	
<p class="first">Sh&icirc;n is distinguished from S&icirc;n by a triangle of dots over the teeth (as with Tha or Z&#846;ha). To my ear it makes sense that the Sh sound would be represented like an S with something added. Sh&icirc;n sounds heavier, thicker, as if it utilized more of the voice-making apparatus. Arabic adds the three dots to Sin (as we add the letter H next to the letter S).&nbsp;</p>
<p>In manuscripts of sufficient age you will also see the clearer sibilant S&icirc;n carrying the same three-dot load, but underneath, i.e., <strong>&#1691;</strong>, (no doubt to make the difference between S&icirc;n and Sh&icirc;n unmistakable). In contemporary Turkish (in Roman letters), the SH sound is represented by &#351;, an S with a cedilla, as in <em>&#351;a&#351;mak</em>, to be surprised, or<em> &#351;i&#351;lemek</em>, to pierce to stab, or <em>&#351;i&#351;</em>, a skewer, as in <em>&#351;i&#351;kebap</em>.&nbsp;</p>
<h3>Spring</h3>
<p>The great Greek poet Constantine Cavafy lived in Alexandria. He knew enough Arabic to entitle one of his early poems (1890s), &laquo;&Sigma;&alpha;&mu; &epsilon;&lambda; &Nu;&epsilon;&sigma;&iacute;&mu;&raquo; (<em>Sam el Nes&icirc;m</em>), the name of an Egyptian spring festival. Or almost the name, since the festival is properly speaking <em>Shamm al-nas&icirc;m</em>, with a Sh&icirc;n. You cannot blame him, as there is no SH sound in Greek.</p>
<p><em>Shamma</em> in Arabic means to sniff or breathe in. <em>Shamm al-Nasim</em> means &ldquo;inhaling the air,&rdquo; &ldquo;enjoying the air,&rdquo; to greet the coming of spring. It can be traced back, before Arabic, to a word with a similar sound, in ancient Egyptian, a proper noun Shemu, the season between May and September. <em>Shamm al-Nas&icirc;m</em> is observed by both Christians and Muslims according to the Coptic calendar, the day after Coptic Easter. Edward Lane, writing in 1834, translates <em>shamm al-nasim</em> &ldquo;smelling of the Z&#846;ephyr&rdquo;: &ldquo;the citizens of Cairo ride or walk a little way into the country, or go in boats, generally northwards to take the air... The greater number dine in the country or on the river&rdquo; (Lane, 483). It is, Lane adds, a festival observed with persistence: &ldquo;This year (1834) they were treated with a violent hot wind, accompanied by clouds of dust, instead of the <em>neseem</em>; but considerable numbers, notwithstanding, went out to &lsquo;smell&rsquo; it.&rdquo;&nbsp;</p>
<p>Cavafy didn&rsquo;t keep &ldquo;<em>Sam el Nes&icirc;m</em>&rdquo; in his complete works, perhaps because the premise is too simple. (It&rsquo;s a poem which says this is a time of celebration, but down deep we know we&rsquo;ll return to our usual grim lives soon enough. Or, more personally, &ldquo;it&rsquo;s their celebration, not mine.&rdquo;) There are many ways to describe the grain of daily life in a culture other than ours; you can&rsquo;t help but suspect that even in the most neutral descriptions there is something suspicious or demeaning. If Cavafy knew the etymology, as is likely enough, it would have been possible to make more use of the fact that the contemporary festivals traced back pre-Islamic sources. Poets (<strong>&#1588;&#1593;&#1585;&#1575;&#1569;</strong>, <em>shu&lsquo;r&acirc;&rsquo;</em>) love that.</p>
<p class="illo"><img src="../_img/shin2.png" width="650" /></p>
<h3>Sub</h3>
<p>A <strong>&#1588;&#1583;&#1577;</strong>, <em>shadda,</em> is a diacritical mark used to mark a double letter. With the Roman alphabet we show double letters by writing the two single ones next to one another (as in &ldquo;accompany, &ldquo;little&rdquo; or &ldquo;letter&rdquo;), but Arabic is more efficient. You don&rsquo;t use the <em>shadda</em> (or<em> tashdid</em>) all the time, but in cases of potential confusion or simply to be meticulous, it&rsquo;s common enough. <em>Shadda</em> could be written <strong>&#1588;&#1583;&#1617;&#1577;</strong>. (The <em>shadda</em> looks like a miniature <strong>&#1587;</strong>; I&rsquo;m sure there&rsquo;s a reason.) A <strong>&#1588;&#1591;&#1617;</strong>, <em>sha&#7789;&#7789;</em> , is a shore, a coast. <em>Sha&#7789;&#7789; al-&lsquo;arab</em> is where the Tigris and Euphrates rivers converge. The verbal stem, <em>sha&#7789;&#7789;a</em> (spelled like the noun &mdash; (<strong>&#1588;&#1591;&#1617;</strong>), is &ldquo;to go to extremes, exceed proper bounds, to digress.&rdquo; The verb <strong>&#1588;&#1617;&#1585;&#1617;</strong> <em>sharra</em>, is &ldquo;to be bad, evil.&rdquo;<em> Sharr</em> (<strong>&#1588;&#1617;&#1585;&#1617;</strong>) is the noun for evil or mischief, injustice, harm or damage.&nbsp;</p>
<p>A friend tells me that the letter Sh&icirc;n is the letter of the suspect or questionable. <em>Shu&rsquo;m</em> is bad luck, a bad omen. (A <em>mutash&acirc;&rsquo;im</em> is a pessimist.) <em>Shirk</em> is idolatry or polytheism, usually used negatively. <em>Sham&acirc;t </em>is Schadenfreude. Shay&#7789;&acirc;n is the devil (or a devil, one among others). <em>Shay&#7789;&acirc;n</em> could possibly be derived from an Arabic stem, but it seems pretty clearly a loan word. (I&rsquo;ve run into a number of possible sources, but whatever it is, it is probably the same origin that gives us &ldquo;Satan&rdquo; -- Greek &Sigma;&alpha;&tau;&acirc;&nu;).&nbsp;</p>
<p>There is a four-consonant verbal stem, SH-R-M-&#7788;, which gives you <strong>&#1588;&#1585;&#1605;&#1591;</strong>, <em>sharma&#7789;a</em>, to tear to shreds. It is related to the noun <em>sharm&ucirc;&#7789;a</em> (<strong>&#1588;&#1585;&#1605;&#1608;&#1591;&#1577;</strong>), a shred or a tatter, but you are much more likely to hear it as the word for a prostitute. Like many four-consonant stems, it seems to be based on a loan word, in this case <em>sharm</em> in Middle Persian, &ldquo;shame.&rdquo;</p>
<p>At some point in their history, books in the category &ldquo;unclassifiable&rdquo; become a genre. &ldquo;Unclassifiable&rdquo; is a category, but probably not the same as a genre. With a lot of unusual books, it can take a while before we know where to put them. Perhaps Ahmad Faris Ash-Shidy&acirc;q&rsquo;s always surprising <em>Al-S&acirc;q &lsquo;al&acirc; al-s&acirc;q</em>,<em> Leg</em> <em>over leg</em> (1955), is still waiting for a place to live. It has a plot, the growth and education of a young man named Al-F&acirc;riy&acirc;q (a variant of the author&rsquo;s name), but the biographical episodes are not what you remember most. It&rsquo;s the digressions. A sentence may be interrupted with a list pages long. One chapter begins &ldquo;If anyone read the end of the previous chapter and then his servant came and called him to dinner, causing him to leave the book and rise...&rdquo; (there follows a two-page list of things that might have happened to interrupt, some of them mysterious little stories in themselves, and concludes), &ldquo;...he will certainly have forgotten all the physical and moral incidents which have befallen the F&acirc;riy&acirc;q...&rdquo; (trans. the late Humphrey Davies, pp. 55-56). Then again, there is a chapter five lines long (entitled <em>F&icirc; l&acirc; shay&rsquo;</em>, &ldquo;On Nothing&rdquo;). <em>Leg over leg</em> has predecessors. Readers have suggested the unclassified Rabelais, which makes sense (though lately Rabelais has been assigned a genre, &ldquo;carnivalesque&rdquo;) and Lawrence Sterne (novel, sort of). A Spanish friend suggests <em>Don Quixote</em> (proto-novel?). One or all of them could be influences. Shidy&acirc;q&rsquo;s <em>shuhra,</em> his reputation, hasn&rsquo;t suffered. Literary histories list him regularly, and don&rsquo;t quite know how to judge him. If there is a dilemma, there is, as Kamran Rastegar has suggested (in the first authoritative study of <em>Leg over leg</em>), a targeting issue: &ldquo;Intentionally obscure, Shidy&acirc;q&rsquo;s work by no means anticipates a single readership, which may be why some scholars have somewhat plaintively seen him to have &lsquo;<em>almost</em> achieved greatness&rsquo;&rdquo; (<em>Literary Modernity between the Middle East and Europe</em>, 112).</p>
<p>The name <strong>&#1588;&#1583;&#1740;&#1575;&#1602;</strong>, Shidy&acirc;q is not as strange and unclassifiable as <em>Al-S&acirc;q &lsquo;ala al-s&acirc;q</em>, but it is not a common name, and it doesn&rsquo;t really sound Arabic. After you ask around from friends who know these things, you find that <em>shidy&acirc;q</em> is a loan word, meaning a role in the Orthodox church. Shidy&acirc;q was a Christian most of his life (he converted to Islam in 1860): a <em>shidy&acirc;q </em>is a sub-deacon, a loan word from Syriac. Syriac borrows the word from Greek &delta;&iota;&aacute;&kappa;&omicron;&nu;&omicron;&sigmaf;, <em>di&aacute;konos</em> (a deacon), which looks a little like the English word &ldquo;deacon&rdquo; (also German <em>diacon</em>, French <em>diaconat</em> or Italian <em>di&aacute;cono</em>). Then there is the prefix SH, which must mean something like &ldquo;sub-,&rdquo; but it remains an SH which is, for me at least, an unknown.</p>
<h3>X</h3>
<p>Sh&icirc;n is for <strong>&#1588;&#1610;&#1569;</strong> , <em>shay&rsquo;</em>, the word for &ldquo;thing&rdquo; in Arabic. It can be used to form a negative, as in Cairo dialect, where one produces a &ldquo;not&rdquo; by putting a negative particle (<em>ma</em>, ما) in front of a word and -<em>sh</em> at the end. That sh sound is short for <em>shay&rsquo;</em>, as we might say &ldquo;not a thing&rdquo; or in French &ldquo;<em>ne... pas</em>&rdquo; (&ldquo;not a step&rdquo;). Thus <strong>&#1605;&#1593;&#1604;&#1588;</strong>, <em>ma&lsquo;lish</em>, &ldquo;it doesn&rsquo;t matter&rdquo; (literally <strong>&#1605;&#1575; &#1593;&#1604;&#1610;&#1607; &#1588;&#1740;&#1569;</strong> &ldquo;there is nothing on it&rdquo; or perhaps &ldquo;nothing to it&rdquo;) or <strong>&#1605;&#1601;&#1610;&#1588;</strong>, <em>maf&icirc;sh,</em> &ldquo;there isn&rsquo;t any&rdquo; (literally <strong>&#1605;&#1575; &#1601;&#1610;&#1607; &#1588;&#1740;&#1569;</strong> , &ldquo;there is nothing in it,&rdquo; &ldquo;nothing there,&rdquo; or a whole series of other negations. (It is one of the two words G&eacute;rard de Nerval learns in his <em>Voyage en Orient</em>, translating &ldquo;pas du tout.&rdquo; His source is the woman he has taken on as a slave in Cairo.)</p>
<p>Among the many uses of <strong>&#1588;&#1610;&#1569;</strong>, like &ldquo;thing&rdquo; in any language, is to refer to the undefined: &ldquo;some thing,&rdquo; &ldquo;any thing.&rdquo; It was used that way in Al-Khwarizm&icirc;&rsquo;s mathematics. Twenty-eight plus <em>shay&rsquo;</em> equals thirty-two. &ldquo;Twenty-eight plus <em>some thing</em> equals thirty-two.&rdquo; We would write it as 28 + x = 32, with the letter X instead of <em>shay&rsquo;</em>.</p>
<p>The story goes that &ldquo;x&rdquo; as the translation of <em>shay&rsquo;</em> is the result of a linguistic mismatch. The mismatch is, the story goes, that the Sh&icirc;n sound does not exist in Spanish (or in Latin, or for that matter in Greek), and consequently when translators at the Toledo School of Translation, founded by Alfonso in the 13th century, translated Muhammad ibn Musa Al-Khwarizmi into either Castilian or Latin, the <strong>&#1588;</strong> sound presumably baffled them. The story continues that they had to borrow a letter which represented a sound close to it, CH (as in &ldquo;chill&rdquo; or &ldquo;chore&rdquo;), and chose the letter X because the Greek letter Chi was (supposedly) pronounced that way. In another version X was pronounced that way (SH) in Spanish. (X can be the SH sound in some dialects, I am told, as with the city Xela in Guatemala.) Terry Moore (the science journalist, not the graphic novelist) recounts the story in an article on the subject in <a href="https://cosmosmagazine.com/mathematics/why-x-marks-unknown-0"><em>Cosmos</em> magazine</a>. He concludes &ldquo;X is the unknown because you can&rsquo;t say <em>sh</em> in Spanish.&rdquo;&nbsp;</p>
<p>I would very much like that explanation to make sense, since it is, after all, a proof by linguistics, but the theory doesn&rsquo;t explain why a translator would want to convey the pronunciation of <em>shay&rsquo;</em> at all, rather than just translating it. A word meaning &ldquo;thing,&rdquo; after all, exists both in Spanish (<em>cosa</em>) and in Latin (<em>res</em>). What could be easier? A translator is not obliged to transliterate. Meanwhile, the Greek letter X (Chi) is definitely not pronounced like our SH. (It&rsquo;s pronounced like Arabic <strong>&#1582;</strong>, KH. That&rsquo;s why the KH sound in Arabic is sometimes represented in English transliteration by an X.) The first Latin translation of Al-Khwarezmi that I know of, <em>Liber algebrae et almucabola</em>, was by Robert of Chester (12th century), presumably a speaker of English. SH would not have been a mystery to him. Middle English had a perfectly usable SH sound. He wouldn&rsquo;t have needed Greek Chi even if he wanted to transliterate.&nbsp;</p>
<p>That <em>shay&rsquo;</em> became X there is no doubt. The letter X used to represent the unknown, our equivalent of Al-Khwarezmi&rsquo;s <strong>&#1588;&#1610;&#1569;</strong>, is said to be a 17th-century development initiated in Descartes&rsquo; book on geometry. (<a href="https://gizmodo.com/why-do-we-use-the-letter-x-to-represent-the-unknown-1588933259">Gizmodo.com</a> seems a trustworthy source on this.)&nbsp;</p>
<p><a href="https://legacy-www.math.harvard.edu/~knill/teaching/summer2019/exhibits/algebra/AlgebraMohammedBenMusa.pdf"><em>The Algebra of Mohammed Ben Musa</em></a>, an 1831 translation by Frederic Rosen, has no trouble simply translating<em> shay&rsquo;</em> into English as &ldquo;thing&rdquo;: thus, in his translation, the equation we would describe as (10 &ndash; x) (10 + x) takes on a perfectly comprehensible form, even in English: &ldquo;If the instance be, &lsquo;ten minus thing&rsquo; to be multiplied by &lsquo;ten and thing,&rsquo; then you say &lsquo;ten times ten is a hundred, etc....&rsquo;&rdquo; (25).</p>
<p class="illo"><img src="../_img/shin3.png" width="550" /></p>
<h3>Sweet</h3>
<p>The stem SH-K-R means &ldquo;to thank.&rdquo; <em>Shukran</em> in Arabic, the most frequently heard term for &ldquo;thank you,&rdquo; is its simplest noun form: <em>shukr</em>, thankfulness, plus an accusative ending, a kind of adverbial &ldquo;thankfully,&rdquo; &ldquo;with thanks.&rdquo; As the word emigrates it could be a lesson in what happens when a term in Arabic becomes a loan word. In Urdu it gets a new suffix, <em>shukria</em>. In Persian the commonest thank-you is an adjective form from the same stem, <em>mutashakker,</em> with the Persian verb &ldquo;to be&rdquo; added, <em>mutashakker-am</em>, &ldquo;I am thankful.&rdquo; In Turkish the form is <em>te&#351;ekk&ucirc;r ederim</em>, &ldquo;I thank you.&rdquo;&nbsp;</p>
<p class="illo"><img src="../_img/shin4.png" width="300" align="right" style="margin-right:-80px" /></p>
<p>In Persian <em>shekar </em>is sugar (no connection to <em>shukr</em>). When it became a loan word in Arabic, the SH became an S. Arabic has the linguistic apparatus to retain the SH, but in this case it didn&rsquo;t. And so, Persian <em>shekar </em>became in Arabic <em>sukkar</em>. It was absorbed into a pre-existent stem, S-K-R, to be drunk, confused, disoriented, and led a double life. <em>Sukrat al-mawt</em> in the Qur&rsquo;&acirc;n is the confusion or stupor of death (Q 50.19). There is in classical Greek a word &sigma;&iacute;&kappa;&epsilon;&rho;&alpha;, <em>s&iacute;kera</em>, a sweet alcoholic drink. It has been suggested that it is a loan word from a Semitic stem. It seems reasonable. If Arabic <em>sukkar </em>and<em> sikera </em>are in fact cognates, it leads us to imagine the occasion, tavern, conflict or mixed party where Greek speakers and fellow drinkers who spoke Arabic might have had a conversation in which the word came up and the Greek speakers liked the sound. </p>
<p><em>Sh&icirc;r</em> in Persian is milk, also proverbial for sweetness. (I shouldn&rsquo;t simplify the story. <em>Sh&icirc;r</em> also means &ldquo;lion&rdquo; and&ldquo;water tap.&rdquo; Why not?) <em>Shir</em> takes an adjective form (and name), <em>shirin</em>, &ldquo;sweet.&rdquo; Another Sh&icirc;n word represents more intense sweetness. In the last chapter of <em>Candide</em>, Candide and his companion Martin famously get the idea to focus on cultivating their garden. They are living in Istanbul: the idea comes from a Turkish farmer who invites them in to eat with his family. The first items on the menu are &ldquo;plusieurs sortes de sorbets qu'ils faisaient eux-m&ecirc;mes,&rdquo; &ldquo;all sorts of <em>sorbets</em> which they made themselves.&rdquo; The immediate ancestor of <em>sorbet </em>is Turkish, <em>&#351;erbet</em> (earlier still, Persian,<em> sharbat</em><strong>).</strong> An earlier predecessor is the Arabic verb <em>shariba</em>, to drink. <em>Shar&acirc;b</em> is a general word for a beverage. (In Persan it means &ldquo;wine.&rdquo; English &ldquo;syrup&rdquo; comes from the same stem. &ldquo;Syrup&rdquo; in the sense we use the word would be something like the Persian Sh&icirc;n word <em>sh&icirc;reh</em> (from <em>sh&icirc;r</em>).&nbsp;</p>
<p><em>Sharibtu</em>: I drank. <em>Sharibn&acirc;</em>: We drank. A particularly famous line from the great thirteenth-century mystical poet &lsquo;Umar Ibn al-F&acirc;ri&#7693; shows how the word can be laundered, so that drinking and getting drunk are ironic ways to describe the mystical exercises of<em> dhikr</em> and the experience of ecstasy:</p>
<blockquote>
<p><strong>&#1588;&#1585;&#1576;&#1606;&#1575; &#1593;&#1604;&#1740; &#1584;&#1705;&#1585; &#1575;&#1604;&#1581;&#1576;&#1740;&#1576; &#1605;&#1583;&#1575;&#1605;&#1577;<br />
</strong><strong>&#1587;&#1705;&#1585;&#1606;&#1575; &#1576;&#1607;&#1575; &#1605;&#1606; &#1602;&#1576;&#1604; &#1571;&#1606; &#1740;&#1582;&#1604;&#1602; &#1575;&#1604;&#1705;&#1585;&#1605;</strong></p>
<p><em>Sharibn&acirc; &lsquo;al&acirc; dhikri al-hab&icirc;bi mud&acirc;ma<br /></em><em>Sukirn&acirc; bi-h&acirc; min qabli an yukhlaq al-kirm</em></p>
<p>[In memory (<em>dhikr</em>) of the beloved / we drank (<em>sharibn&acirc;</em>) a wine; / we were drunk with it before creation of the vine &ndash; tr. Emil Homerin, 54]</p>
</blockquote>
<p>The crescent moon, Ibn al-F&acirc;ri&#7693; continues, was a cup for that drink, a crescent that fills up with light from the <em>shams</em>, the sun, like a soul imbibing illumination.</p>
<h3>Sunrise</h3>
<p>In the pantheon of supernatural figures who govern the plot of <em>Gilgamesh</em> there is a deity named Shamash, a god connected somehow with the sun. Gilgamesh and Enkidu pray to him when they go out to fight Humbaba. It&rsquo;s easy to see a recognizable Semitic stem in Shamesh if we think of <em>shams</em> in Arabic, Sh&icirc;n word for the sun. In adjective form, <em>shams&icirc;</em>, it describes a solar calendar, as distinct from a <em>qamar&icirc;</em> or lunar calendar.&nbsp;</p>
<p class="illo"><img src="../_img/shin5.png" width="300" align="right" style="margin-right:-80px" /></p>
<p>The relations of sun and moon are everywhere. You&rsquo;ll find them in the first lesson of a course in Arabic, where you learn that there are two categories of letters, fourteen each, categories named for the moon and sun, differentiated by the way they react when they are placed directly after the letter L&acirc;m of the definite article, -<em>al</em>. The Moon letters, <em>al-&#7717;ur&ucirc;f al-qamariyya</em> (Alif, Ba&rsquo;, Jim, &#7716;a&rsquo;, Kh&acirc;&rsquo;, &lsquo;Ayn, Ghayn, F&acirc;&rsquo;, Q&acirc;f, K&acirc;f, M&icirc;m, Waw, Yay and Ha [hawwaz]) leave the L alone, as in the words <em>al-&#7717;ur&ucirc;f, </em>&ldquo;the letters,&rdquo; and<em> al-qamariyya </em>&ldquo;the lunar ones,&rdquo; where the L remains intact. The Sun Letters, <em>al-&#7717;ur&ucirc;f al-shamsiyya</em> (Ta, Tha, D&acirc;l, Dh&acirc;l, Ra, Z&#846;a, S&icirc;n, Sh&icirc;n, &#7778;ad, &#7692;al, &#7788;a, Za, L&acirc;m and N&ucirc;n), make the L&acirc;m of <em>al</em>- disappear, or rather, assimilate. Thus the term written <em>al-&#7717;ur&ucirc;f al-Shamsiyya</em> in official transcription is pronounced differently, <em>al-&#7717;ur&ucirc;f ash-shamsiyya</em>. Shamm al-Nas&icirc;m is pronounced <em>Shamm an-nas&icirc;m</em>. <em>Al-ra&#7717;m&acirc;n al-ra&#7717;&icirc;m</em> is <em>Ar-ra&#7717;m&acirc;n ar-ra&#7717;&icirc;m</em>. <em>Kawkab ash-Sham&acirc;l </em>is the North Star.</p>
<p><em>Ash-Sham&acirc;l</em> is the north, but it is also the word for &ldquo;the left&rdquo; (as opposed to <em>Al-yam&icirc;n</em>). A map with north on the left would put east at the top (perhaps because that is where sunrise takes place?). Actually, in vintage maps it&rsquo;s the norm, oriented with East at the top and West at the bottom. No doubt there is a cause and effect here &ndash; whether the map affects the use of the word or the other way around. (It has nothing to do with Mecca, by the way. Maps east of the Holy Land are still likely to have East at the top and North on the left.)&nbsp;</p>
<p>&ldquo;East&rdquo; is <strong>&#1588;&#1585;&#1602;</strong>, <em>sharq</em>, whose stem (SH-R-Q) means in its verbal form &ldquo;to rise,&rdquo; as in &ldquo;sunrise.&rdquo; The noun form <strong>&#1605;&#1588;&#1585;&#1602;</strong>, <em>mashriq</em> is the place of sunrise, another word for the East, the land of the rising sun. (The etymological basis is comparable to our word &ldquo;Orient,&rdquo; from Latin <em>orior</em>, to rise. The opposite, &ldquo;Occident,&rdquo; is from Latin <em>occidere</em>, to fall down, to set.) A <em>Sharq&icirc;</em> is a person from the east (an &ldquo;oriental&rdquo;). Our word &ldquo;saracen&rdquo; may come from its plural, <em>sharq&icirc;y&icirc;n</em>. (The OED is doubtful about this.) A <em>mustashriq</em> is someone whose demeanor is characteristic of the east, a synonym for &ldquo;oriental,&rdquo; but, by a grammatical transformation I don&rsquo;t really understand, it also designates the contrary, a student of the Middle East, an orientalist, someone who looks at the Middle East from outside. <em>Al-istishr&acirc;q</em> is the study of the East, orientalism. It is the word used to translate into Arabic Edward Said&rsquo;s term &ldquo;orientalism.&rdquo;&nbsp;</p>
<p>We know the argument, and we rehearse it repeatedly &ndash; that students of the field tend to distance themselves, to speak of their subject with smug superiority. (I&rsquo;ve already rehearsed it once today.) Said&rsquo;s argument is nuanced: he acknowledges that there are experts who resist the pressures towards ethnocentrism, over-simplification and the weakness of projecting our cultural anxieties on non-Europeans. The focus of <em>Orientalism</em>, the book, however, is centered on the expert who gives in to the traditional temptation (of western condescension). It requires a very powerful book to counterbalance a whole tradition. A slowly building, towering argument, however logical, isn&rsquo;tt necessarily enough. <em>Orientalism</em> accomplishes this, however, in briefer form. What drives his argument is a wide, powerful idea, but an idea that narrows to a sharp point. The word &ldquo;orientalism&rdquo; is the sharp point.</p>
<p>We may underestimate the sheer brilliance of that title. Titles can sum up the argument, but this one propels it. &ldquo;Orientalism&rdquo; (the word) before <em>Orientalism</em> (the book) had been a colorless, antiquarian term, like the half-defined thing it described, amorphous and seemingly innocent. But to make it the name of a political phenomenon gives it a rare weight. The word takes on fetish value, its own force of gravity. <em>Orientalism </em>simply makes it impossible for anyone to use the word &ldquo;orientalism&rdquo; again without taking Edward Said&rsquo;s use of it into account.&nbsp;</p>
<p class="illo"><img src="../_img/shin6.png" width="200" align="right" style="margin-right:-80px" /></p>
<p>The ability of a word to travel from one context to another is a sign of its power. There are no guarantees, however, that once broken loose, charged with that rhetorical intensity, the word will retain its nuances. In academic discourse the word &ldquo;orientalism&rdquo; has taken simpler and simpler, less and less nuanced forms. It can be wielded as an insult in ways that would have surprised Edward Said. Come for the concept; stay for the slogan.</p>
<p>The evolution &ldquo;Orientalism&rdquo; has undergone is a process like that of the word <em>jihad.</em> <em>Jih&acirc;d</em> narrowed from a general term used to describe religious striving, a term with both an outward and an inward meaning, until it has come to represent, to the ignorant, nothing more than a terrorist imperative. (The shrunken form of <em>jih&acirc;d</em> is used this way in public discourse, to describe any violence with religious motives.) One might want to reel it back from the simplified meaning, but is probably impossible: once a word has taken on its narrow, more powerful form, we&rsquo;re stuck with it. It will keep its authority. We&rsquo;re not going to defuse it.&nbsp;</p>
<p>Sh&icirc;n word <em>shaykh</em> (anglicized as sheik) is used for more than one level of authority. It&rsquo;s not a word that possesses power, but a word which describes it. Etymologically a <em>shaykh</em> (Turkish <em>&#351;eyh</em>) simply means someone &ldquo;of a certain age&rdquo; (from Arabic SH-Y-KH, to grow old). It can mean an old man. (The three men who arrive at the house of the three ladies of Baghdad in the <em>1001 Nights</em> are<em> shuy&ucirc;kh</em>, <em>shayk</em>s.) It can be the head of a family or a tribe (our word &ldquo;elder&rdquo;). It can mean a ruler of a sheikdom (a <em>mashyakha</em>). It can mean a scholar in theology. It can mean the head of a Sufi order.&nbsp;</p>
<p><em>Sh&acirc;h</em> is a word with less free play. It refers to a king, a sovereign, very much a Persian form of authority, with an etymology rooted in old Indo-European forms. (The name we spell Xerxes is from the same stem.) Perhaps its limited semantic field also makes it a brittle term. When the ruler of Iran was deposed in 1979 the word fell with him. Bandar Shah, once a port on the shore of the Caspian, is now Bandar Turkmen. The extraordinary Masjad-e Sh&acirc;h mosque in Esfahan (Royal Mosque in English) is now the Mashjad-e Em&acirc;m.</p>
<p class="illo"><img src="../_img/shin7.png" width="450" /></p>
<h3>Tree of Pearls</h3>
<p>Sometimes you don&rsquo;t know what to call a person in power. A <em>shajara </em>is a tree, a <em>shajarat an-nasab</em> is a genealogical tree. Shajarat ad-Durr, a tree of pearls, is a name of importance to the history of royal authority in the Arab world. Fatma Mernissi tells the story of the woman named <em>Shajarat ad-Durr</em> as part of a demonstration that, though most rulers have been men, in practice there have also been Arab women who occupied the throne and taken on the role of queen, but that there is no tradition to validate it, and thus no language to account for it. Mernissi asks, what do you call a queen? The phenomenon of Shajarat ad-Durr&rsquo;s rise to power in 1249 wasn&rsquo;t immediately a problem of naming. Before finding a title for her you have to wonder how she got there, what networks of power made it possible. She was born a slave, taken as a concubine by Sultan A&#7779;-&#7778;alih Najm Ad-Din Ayyub. When he died of sickness during the campaign against Louis ix&rsquo;s crusade (the seventh, 1249-50), she concealed the fact of his death and took power behind the scenes. It&rsquo;s only when she made her control public that it became possible to ask Fatima Mernissi&rsquo;s question.&nbsp;</p>
<p>The power which brings her to the court is first the companionship of the sultan. The second opportunity is the power vacuum created by his death, which wouldn&rsquo;t have been sufficient in itself; she has to demonstrate her intelligence. A&#7779;-&#7778;&acirc;li&#7717;&rsquo;s son could have claimed the right to succeed him, but he was assassinated. (If you read enough accounts you hear claims that she arranged it.) The additional vacuum created by the disappearance of still another male claim to authority would not have been sufficient cause for her rise to power, but her popularity with the army adds to the equation. (I can&rsquo;t say how she became popular with the army: in this story it&rsquo;s a given.) Once she&rsquo;s in power we can consider the need for a title. It couldn&rsquo;t be <em>khal&icirc;fa</em>. There was a weak caliph in Baghdad, Musta&lsquo;&#7779;im, who presumably ruled the entire Islamic world under that title. (He wouldn&rsquo;t rule for long.) Shajarat ad-Durr opted for the generic title <em>malika</em>, the feminine form of <em>malik</em>, king. (One also sees her referred to as <em>sultana,</em> holder of power.) She ruled alone for eighty days and then married &lsquo;Izz ad-D&icirc;n Aybak, the head of the army, in order to stay on as an unacknowledged counselor. (It ended badly.)</p>
<p>There are coins in which her name is found, but they were struck after the eighty days of her reign. Her name is displayed jointly with that of her second husband &lsquo;Izz ad-D&icirc;n. You can see poorly focused photos of the coin <a href="https://www.google.com/search?q=Genzoman+Shajarat+al-Durr&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwjQyOOYk6foAhWSLc0KHW7LALQQ_AUoAnoECAYQBA&amp;biw=1217&amp;bih=615#imgrc=Es2b4hwOvQ0pLM">online</a>.</p>
<p>They look clumsily cut, with awkward calligraphy: <em>al-Musta&lsquo;&#7779;imiyah a&#7779;-&#7778;alihiyah Malikat al-Muslim&icirc;n walidat al-Malik al-Man&#7779;&ucirc;r Khal&icirc;l Am&icirc;r al-Mu'min&icirc;n</em>: (The Musta&lsquo;&#7779;imiyyah, the pious Queen of the Muslims, Mother of King Al-Mansur Khalil [she had a son named Khalil],<em> am&icirc;r</em> of the faithful). That first adjective, <em>al-musta&lsquo;&#7779;imiyyah</em>, is the adjective form of the caliph&rsquo;s name, Musta&lsquo;&#7779;im. Using it as her title was, as Mernissi points out, &ldquo;a pathetic admission of her weakness, a desperate attempt to gain his goodwill&rdquo; (90). Though Musta&lsquo;&#7779;im was a weak ruler, in his role as commander of the faithful he still had the power to humiliate her. The greater, more material insult was his ability to shut down her role as<em> malika</em>, &ldquo;queen.&rdquo; (It&rsquo;s with this humiliation that the eighty days ended.) Musta&lsquo;&#7779;im&rsquo;s judgment on her claim to power in Egypt was that &ldquo;he was ready to provide them with some capable men, if no more existed in Egypt, since they were reduced to choosing a woman&rdquo; (Mernissi 29). Mernissi also adds that, seven years later, Musta&lsquo;&#7779;im was killed when Hulagu invaded Baghdad and destroyed his kingdom. (The Mongols, by the way, never succeeded in occupying Egypt.)</p>
<p>Musta&lsquo;&#7779;im revealed the gap in Shajarat ad-Durr&rsquo;s power. Her dilemma of improvising a term (<em>malika</em>) for queen demonstrates the linguistic power vacuum. Still, the absence of explicit definition of her role can be a gap in the wall which hems her in. The unstated, the unclassifiable, can be an advantage. One of the sources of power is a lapse of attention on the part of one&rsquo;s opponent. She certainly won out in the memory of storytellers.</p>
<p>Sultan A&#7827;-Z&#846;&acirc;hir Baybars al-Bunduqdari (d. 1277), came to power in Egypt in 1260, four years after Shajarat ad-Durr&rsquo;s death<strong>, </strong>three years after the fall of Baghdad. The story of his life generated a long epic romance, <em>S&icirc;rat a&#7827;-</em>Z<em>&acirc;hir Baybars</em> (a <em>s&icirc;ra</em> being a story of heroism). Among a multitude of characters in the romance is a character named Shajarat ad-Durr. In this version she is a daughter of the caliph Muqtadir (895-932 -- it&rsquo;s an anachronism). A&#7779;-&#7778;&acirc;li&#7717; Najm ad-D&icirc;n marries her in order to establish his legitimacy as Sultan in Egypt. She protects the hero Baybars; &lsquo;Izz ad-D&icirc;n Aybak appears as the heavy, a claimant to the throne, killed by Shajarat ad-Durr.&nbsp;</p>
<p>Shajarat ad-Durr is also the subject of a historical novel by Jurji Z&#846;aydan (1861-1914). To read it (in an unusually beautiful English translation, by Samah Selim) is to see an additional account of power. It&rsquo;s in the style of Walter Scott or Cooper, a translation of historical events into the mood of romance. In a romance, no matter how accurate the historical background, the sources of power are personal. We learn about her rivalry with the envious concubine Sallafa, who engineers a break between the heroine and her faithful confidante Shwaykar. There are only very good or very bad characters.&nbsp;</p>
<p>The name still hasn&rsquo;t worn out completely. Shajarat ad-Durr shows up in a cute pixar-style image on <a href="https://www.rejectedprincesses.com/wp-content/uploads/2014/07/shajaraldurr-354x500.jpg">the web page</a> by Jason Porath. She is also one of the characters depicted in a repertoire of drawings by the graphic artist Gonzalo Ord&oacute;nez Arias (pen-name, Genzoman). In his image, she is dressed superhero-style, not warmly, unencumbered, mostly in just a cape and billowing <em>shelv&acirc;r</em> which reaches up a few inches above the knee. She flourishes an oddly shaped <em>shamshir</em>, a scimitar. For some reason the blade has a notch like a bottle opener and rows of metal rings at the lower and upper ends (three each). She stands with one foot on a little strip of rubble. The pyramids are in the background, underneath what seems an incoming sand storm. Her black hair flutters behind her like the cape, as if with a mind of its own. She seems the sort of character who would think in terms of strength rather of strategy.</p>
<h3>Knight&rsquo;s Move</h3>
<p><strong><em>&#1588;&#1593;&#1585;</em></strong>, <em>shi&lsquo;r</em>, is poetry. The same three letters give us <em>sha&lsquo;r</em>, hair. The same stem with still another set of vowels is Shi&lsquo;r&acirc;&rsquo;, the star Sirius, brightest star in the celestial catalog. In a list of the Lord&rsquo;s powers in the sura named The Star (<em>An-najm</em>) &ldquo;He is the lord of Shi&lsquo;r&acirc;&rsquo;&rdquo; (53.49). There may be a link between hair and a star: it is possible to think of brightness as fuzziness, thus the stem Sh-&lsquo;Ayn-R. On the other hand, Arthur Jeffery&rsquo;s<em> Foreign Vocabulary of the Qur&rsquo;&acirc;n </em>psays with certainty that Shi&lsquo;r&acirc;&rsquo; is a loan word from Greek &Sigma;&epsilon;&iacute;&rho;&iota;&omicron;&sigmaf;, <em>se&iacute;rios</em>, &ldquo;hot.&rdquo;&nbsp;</p>
<p>One of the most problematic early caliphs was Mu&lsquo;&acirc;wiyya (602-680), not simply because his name looks so hard to pronounce. (The accent is on the second syllable: Mow-OW-we-ya. In Persian it&rsquo;s Mow-&acirc;vi-YEH.) His rise to power between the assassination of &lsquo;Uthm&acirc;n (656 A.D.) and that of &lsquo;Al&icirc; (661), the period referred to as the first <em>fitna</em> (the first big scandal in the new Muslim community), marks Mu&lsquo;&acirc;wiyya as a brilliant tactician, embodying secular force rather than spiritual authority. He described his philosophy of authority subtly:</p>
<p>I do not employ my sword when my whip suffices me, nor my whip when my tongue suffices me; and were there a single hair (<strong>&#1588;&#1593;&#1585;</strong>, <em>sha&lsquo;r</em>) between me and my subjects, I would not let it be snapped. (Nicholson, <em>A literary history of the Arabs</em>, 194 / Ya'qubi [ed. Houtsma] ii.283, l. 8 seq).</p>
<p>The image of a fragile filament kept intact by a sensitive hand which can loosen its grip or pull tight, in response to a hand on the other side, is an image quite unlike Mu&lsquo;&acirc;wiyya&rsquo;s reputation.&nbsp;</p>
<p>One of the sources of contention between &lsquo;Ali and Mu&lsquo;&acirc;wiya was rule over ash-Sh&acirc;m. (Sh&acirc;m is Syria. Sh&acirc;m&icirc;, is the adjective &ldquo;Syrian,&rdquo; also a term for flat bread, which evidently is thought to be from there.) The most famous Sh&acirc;m&icirc; in English history was Philippe Stamma (d. ca. 1755), who came to England from Aleppo and ended up a regular at Slaughter&rsquo;s Coffee House in St. Martin&rsquo;s Lane (hangout of Hogarth &amp; Thomas Gainsborough). Stamma&rsquo;s notoriety came from his brilliance at chess. His book, <em>Essai sur le jeu des &eacute;checs o&ugrave; l&rsquo;on donne quelques r&egrave;gles pour le bienjouer et remporter l'avantage par des coups fins et subtils, que l'on peut appeler les secrets de ce jeu </em>(1741, translated four years later as <em>The Noble Game of Chess</em>) is famous for having emphasized the importance of the endgame and having devised a notation to show chess moves which is, more or less, the one we still use.</p>
<p>If we wanted to put together an inventory of visitors to Europe from the Arab world, we could include chess itself. It was pretty well known that chess came from the east. (Even the hoax called Maelzel&rsquo;s Automaton Chess Player, which was displayed in Europe and the U.S. from 1770 to 1854, in which an automaton played chess, supposedly in the manner of a computer, but in fact guided by a chess master hidden underneath the apparatus, was presented to audiences by a master of ceremonies in Middle Eastern clothes. It was called The Mechanical Turk.) Wikipedia tells you that Maelzel&rsquo;s spectacle defeated both Napoleon and Benjamin Franklin. Rex Sorgatz, a friend of the Alphabet, pointed out, to my surprise, that Charles Babbage saw the automaton in 1819, shortly before he began work on the Difference Engine (<em>The Encyclopedia of Misinformation</em>, 2018, p. 131).&nbsp;</p>
<p>If you believed it was a machine determining the moves, would you also believe that it was invented east of Europe? If on the other hand you saw through it, would you believe that the invisible chess master was from the Islamic world? You can find lists of the chess masters who were hired to sit in that claustrophobic space, all of whom seem to have been non-claustrophobic Europeans.</p>
<p>During a period when there was an alliance between Charlemagne and the Abbasid empire, the caliph Harun ar-Rashid gave the emperor among other presents (elegant cloth, a water clock, an elephant named Abu &lsquo;Abb&acirc;s) a chess set. So chess, like camels and magic lanterns, became one of those images that represented the middle east as early as the 9th century.&nbsp;</p>
<p>Over time it became familiar and less exotic.&nbsp;</p>
<p>One of Omar Khayyam&rsquo;s quatrains describes us humans as chess pieces and <em>falak</em> (&ldquo;the heavens&rdquo;) as the chess players. (<strong>&#1605;&#1575; &#1604;&#1593;&#1576;&#1578;&#1711;&#1575;&#1606;&#1740;&#1605; &#1608; &#1601;&#1604;&#1705; &#1604;&#1593;&#1576;&#1578; &#1576;&#1575;&#1586;</strong>, <em>M&acirc; lo&lsquo;batg&acirc;nim-o falak lo&lsquo;batb&acirc;z</em>, &ldquo;we&rsquo;re the pieces; the sky is the player,&rdquo; in FitzGerald&rsquo;s paraphrase, &ldquo;But helpless Pieces of the Game He plays/upon this chequer-board of nights and days...&rdquo; FitzGerald 5th edition # 69). And afterwards we get put back, one by one, into the box of non-being (<em>&#7779;and&ucirc;q-e &lsquo;adam</em>). He takes it for granted that we know the game and doesn&rsquo;t even bother to name it. (It&rsquo;s not an uncommon image. The same metaphor occurs in <em>Don Quixote </em>&mdash; Part two, chapter 12 (one of its most beautiful chapters).</p>
<p>Chess is the Sh&icirc;n word <strong>&#1588;&#1591;&#1585;&#1606;&#1580;</strong> <em>sha&#7789;ranj</em>. With five consonants, it&rsquo;s not likely to be an indigenous Arabic word. (William Jones traced it to Sanskrit <em>chaturanga</em>.) As the story goes, the way Ferdowsi tells it in the <em>Sh&acirc;hn&acirc;meh</em>, the king of India sent a chess board and chess pieces as a gift to the Persian king Nushirvan with the challenge to figure out how it&rsquo;s played. They get one hint: &ldquo;the rules are the rules of war.&rdquo; The legendary perfect advisor Bozorjmehr is said to have figured out what the moves must be. The story is doubtful. (It&rsquo;s a lot to expect, of even the best advisors, to determine the rules of chess from the appearance of the board and the shape of the pieces.) Perhaps it would be just as hard to learn military strategy from the rules of chess. There is, however, an example of it.&nbsp;</p>
<p>Philippe Stamma, in <em>The Noble Game of Chess</em>, described a young man in Syria who spent all his time playing chess, for which his father reproached him. The son insisted that chess was useful. The father doubted it and, to straighten him out, sent him on a road trip for business.</p>
<p>When the young man was on his road, the father sent four men after him to rob him. When the son found himself opposed to these robbers, he dismounted quickly, abandoned his horse, and taking refuge behind the walls and hedges, escaped. (<em>Essai sur le jeu des &eacute;checs, </em>157-58, trans. Charles Tomlinson, 75)</p>
<p>Abandoning your horse is a response that could have occurred to anyone, chess player or not, but the son&rsquo;s explanation is an argument for the ability of the imagination to claim its power:</p>
<p>&ldquo;As soon as I was attacked,&rdquo; said he, &ldquo;I bethought myself of an expedient frequently adopted at chess, viz., to sacrifice my horse to save my life and my money: in the same way as at chess I sometimes sacrifice my knight, in order to save my king or my queen...This little story [says Stamma], is far more pleasantly related in the Arabic, in which language the knight [<em>cavalier</em>] is called a horse [<em>cheval</em>].&rdquo; (<em>Essai sur le jeu des &eacute;checs, </em>158-59<em>, </em>trans, Tomlinson, 75)</p>
<p>The names of the pieces retain imagery from the Arab world (and points further east). The knight is <em>faras</em>, the horseman, but we knew that already from the shape of the piece. (We should add that the son in the story sacrificed a horse, not a horse-man.) The rook was a <em>rukh</em> (no idea why), though in contemporary Arabic it is the fortress (<em>&#7789;</em><em>&acirc;biyya</em>). The linguistic dilemma Fatima Mernissi examines, what to call a queen in Arabic, is not an issue in this case. What we call the queen is the <em>waz&icirc;r</em> (Persian <em>farzin</em>), the advisor. The bishop is an elephant (<em>f&icirc;l</em>). The king is a <em>malik</em>, in Persian a <em>sh&acirc;h</em>.</p>

<p class="illo"><img src="../_img/shin8.png" width="600" /></p>


</article>
<cfinclude template="../_footer.cfm">

