<cfset chapter = "Tha"><cfinclude template="../_header.cfm">

<article>

	<h1><a href="/">The Arabic Alphabet: A Guided Tour</a></h1>
	<h4>by Michael Beard</h4>
	<h5>illustrated by Houman Mortazavi</h5>
		
	<div class="illo"><img src="../_img/tha-1a.jpg" alt="tha" /></div>
	<h2>Tha is for Soraya</h2>

	<p class="first">Add a third dot to Ta and we have Tha, the last in the series of plate-shaped letters. Among the commonly taught languages the Tha sound (the unvoiced th- of &ldquo;thin,&rdquo; "path,&rdquo; &ldquo;thud&rdquo; or &ldquo;both&rdquo;) is rare, but standard Arabic shares it with us (and with Greek). In English we use a single pair of letters (T plus H) to represent both Tha and its voiced equivalent (the th- of &ldquo;this,&rdquo; &ldquo;the&rdquo; or &ldquo;either&rdquo;). Standard Arabic has both of the TH sounds in its arsenal, with separate letters for each one. (The voiced sound comes along four or five letters further on.) There was a time when English too had  separate letters for TH and TH (one called &ldquo;thorn,&rdquo; &thorn;, and one called &ldquo;eth,&rdquo; &eth;), but reading English now, of course, if we want to distinguish them we&rsquo;re on our own.</p>
	<p>Ahmad Amin&rsquo;s <em>Q&acirc;m&ucirc;s al-&lsquo;&acirc;d&acirc;t wa al-taq&acirc;l&icirc;d wa al-ta&lsquo;&acirc;b&icirc;r al-misriyya</em> (Dictionary of Egyptian customs, traditions and expressions &mdash;Cairo, 1953), a personal anthology, full of individual reminiscences and oddities, arranged in alphabetical order, admits to a gap in the data. Under the rubric of Tha there are no entries whatever, just a brief note of two sentences explaining that the letter Tha is not pronounced in Egyptian dialect: but that it bifurcates into two more familiar sounds, usually a T (thus <em>thaq&icirc;l</em> becomes taq&icirc;l or, more accurately, <em>ta&rsquo;&icirc;l</em> &mdash; long story) but sometimes into an S sound, so that <em>thaw&acirc;b</em>, a good deed, becomes a <em>saw&acirc;b</em>, in Persian a <em>sav&acirc;b</em>. (In Persian too the letter Tha exists, but the sound &mdash; once a phoneme in Avestan, pre-Islamic Persian &mdash; has not survived. Today Tha in Persian is simply pronounced S, referred to as <em>Se</em> <em>seh-noqteh</em>, &ldquo;the S-sound with three dots.&rdquo;) Since Tha words are peculiarly Arabic, Tha in a Persian, Turkish or Urdu text will be the unerring sign of a borrowed word.</p>
	<p>Tha descends from the same Nabatean letter as Ta. In Arabic it&rsquo;s the extra dot that makes the difference. The three cluster in a triangle, like a stack of cannonballs or oranges. (Tha is for <em>thamar</em>, &ldquo;fruit.&rdquo;) In handwriting the three dots can become (as with Pa) a little circle.</p>

	<div class="illo"><img src="../_img/tha-2.png" width="600" /></div>

	<h3>Three</strong></h3>
	
	<p>Tha is also for <em>thal&acirc;tha</em>, &ldquo;three.&rdquo; <em>Th&acirc;l&ucirc;th</em> is the Christian notion of the trinity. <em>Thul&ucirc;th </em>is the word for a fundamental style of cursive script which developed in the 11th century, whose proportions were developed by the tenth-century calligrapher Ibn Muqla. The threeness of the script must mean something. I don&rsquo;t know it. (Yasin Hamid Safadi, in his always useful <em>Islamic Calligraphy</em>, cites two common explanations, neither very satisfying.)</p>
	<p>There are three Tha animals which show up regularly in folklore and literature. First, Tha is for<em> tha&lsquo;lab</em>, a fox. Foxes are not linked with hen-houses, as they are in English, and there are occasions where they are not wily. In a famous parable (from the great story collection <em>Kalila wa Dimna</em>) a fox attacks a drum hanging from a tree, blowing in the wind, and is disappointed that there is no meat inside. The great 8th-9th-century essayist Al-J&acirc;ḥiẓ says (in &ldquo;The Book of Animals&rdquo;), not so much that the fox isn&rsquo;t wily, but that the dog is more cunning. In the case of Tha animal <em>tha&lsquo;b&acirc;n</em>, &ldquo;snake,&rdquo; cunning is not an issue. Snakes can be negative. (The villain Zahhak in pre-Islamic Iranian myth has snakes growing on his shoulders. They eat human brains.) They can be positive. (The hair of the beloved in romantic poetry &mdash; <em>m&acirc;r-e sar-e zolfat-e tow</em> &mdash; can be compared to a snake simply because it&rsquo;s curled.) Or they can be valued for their antiquity.</p>
	<p>There are commentators who see in Al-J&acirc;&#7717;i&#7827;&rsquo;s writing a precursor of the concept of evolution. Fish, for instance, were originally snakes. The ones who became fish were spurred on by some unnamed influence of the environment. In the Qur&rsquo;&acirc;n, snakes are positive in at least one thing &mdash; that, with divine aid, Moses (as in Exodus 4.2) turned a staff of wood into one (Q 7.107 and 26.32).</p>
	<p>The constellation we know as Taurus is in Arabic <em>Thawr</em>, the Arabic word for bull. The similarity of sounds, <em>taurus</em> and <em>thawr</em>, may attest to a common root, or perhaps a loan word coming from one direction or the other. The animal is not rare in folklore. Not rare at all.</p>
	<p>A census of animals in the mythologies of the ancient world may elicit the question, what is it about bulls anyway? Roberto Calasso&rsquo;s <em>The Marriage of Cadmus and Harmony</em> (1988), his update of Ovid's <em>Metamorphoses</em>, retells the Greek myths with an eye to contemporary themes, and you can&rsquo;t help but notice how many bulls wander in and out of the Greek foundational stories. The palace of Knossos in Crete is famous for the mural which shows an acrobat on the back of a bull. Then there is the Minotaur, half bull; there is the Minotaur&rsquo;s father, all bull; there is Io; then there is the bull which is believed to have been sacrificed in the Eleusinian mysteries. And they are still with us. We have, after all, a continent (Europe) named after a mythological figure (Europa) who wandered across the land mass on the back of a bull, the bull being Zeus in disguise. One of the initial puzzle pieces in Martin Bernal's attempt to reconstruct Mediterranean pre-history in <em>Black Athena</em> (vol. 2 1991) is to connect the bull cults of Crete with those of Egypt as related phenomena. In Zoroastrian tradition the creation of the first man was echoed by the creation of the first bull. After a while you might start to think that the culture of the ancient world was a franchise with only one logo, and this includes the lands we now call the Middle East. An earlier study with a big historical picture, Giorgio de Santillana&rsquo;s <em>Hamlet&rsquo;s Mill</em> (1967), discovers an astronomical logic centering around a bull. His argument has the elegance of a mythological vision which coincides mysteriously with science.</p>
	<p>The scientific part was a prehistoric interpretation of things going on in the sky. It was the decision to locate the beginning of spring at the moment when the sun, in its annual circling of the ecliptic, crossed the celestial equator. (We call it the equinox. The sun crosses the celestial equator twice, once to mark the beginning of autumn, and once to mark the beginning of spring.) When that decision was made, the argument runs, plausibly enough, the point where the two circles intersect in spring was located in the constellation Taurus. In other words, spring came and the celestial year began with a bull, the ox of the Phoenician alphabet.</p>

	<p class="illo"><img src="../_img/tha-3.png" width="350" align="right" style="margin-right:-80px" /></p>

	<p>In De Santillana&rsquo;s argument the bull, gradually, loses its primacy. The year began with Taurus, but as time went by the phenomenon called the procession of the equinox shifted the relation of earth to sky (we&rsquo;re speaking in large units of time here), and the equinox edged over the border of Taurus into the realm of Aries. The bull was now the second sign of the Zodiac. This does not tell us why that particular arrangement of stars came to be called a bull (it doesn&rsquo;t look like one), but, once we just accept the identification, De Santillana&rsquo;s suggestion could explain numerous narratives in which oversize bulls are deposed from positions of authority, like the killing of the bull of heaven by Enkidu in the story of <em>Gilgamesh</em>.</p>
	<p>A <em>thawr</em> figures prominently at the outset of the <em>Thousand and One Nights</em>, even before the numbered nights begin, in the very first embedded tale, told not by Shahrazad but told to her, by her father the <em>vaz&icirc;r</em> (English vizier). When Shahrazad offers to marry king Shahrayar her father is skeptical. After all, Shahrayar has been executing each wife the morning after her wedding night, so we might expect to hear a father at his most persuasive. Shahrayar as a husband would be many steps worse than that high school dropout with the tattoo. The looming threat to Shahrazad, however, becomes a matter for an intellectual debate. In the vizier&rsquo;s story a donkey and a <em>thawr</em> are living on a farm owned by a wealthy merchant who for some reason knows the language of the animals. (Don&rsquo;t ask why.) The <em>thawr</em> complains to his stable-mate, the donkey, how hard the work is when you are hooked up to a yoke plowing all day. The donkey&rsquo;s advice is to pretend being sick, because the farmer won&rsquo;t put a sick animal to work. The <em>thawr</em> follows the donkey&rsquo;s advice and pretends to be sick, with the foreseeable result that the farmer yokes up the donkey to do the same work. We gather that the donkey is less fit for plowing, and ends up even more exhausted than the <em>thawr</em>. What began as a conflict between labor and management becomes a conflict between two of the employees.</p>
	<p>I&rsquo;ve never felt I understood why this story would persuade Shahrazad to abandon her marriage plans, unless her father expects her to hear it as a parable about the danger of unintended consequences. The news circulates around the barnyard that if the <em>thawr</em> doesn&rsquo;t start working again the farmer will sell him to the butcher. (I&rsquo;ve always assumed the donkey started the rumor, but nothing in any of the versions I have read says this explicitly.) So the next time the owner, with his wife, enters the stall the <em>thawr</em> breaks wind as a sign of health and, in Richard Burton&rsquo;s 1885 translation, &ldquo;frisked about so lustily that the merchant laughed a loud laugh and kept laughing till he fell on his back&rdquo; (20).</p>
	<p>After this, there is a sequel, a second story probably more relevant to Shahrazad: the merchant&rsquo;s wife asks him why he laughed, at which point we are reminded that the merchant knows the language of the animals with an unmotivated, off the wall condition that he can&rsquo;t tell anyone about his skill, on pain of death. So when the merchant decides to ignore the prohibition and tell his wife what has happened (evidently people love to tell secrets in spite of anything) this means he must prepare for his own death. But before this can happen he overhears the rooster, with his fifty wives, saying to the farmyard dog that the farmer should keep his silence and beat his wife instead. The message of the vizier&rsquo;s story is, thus, silence: i.e. to let the prohibition stand which forbids us from telling our story. If speech is what will keep Shahrazad alive, this parable conveys the opposite message. Fortunately, you and I already know the story. If Shahrazad had agreed with the rooster&rsquo;s advice (to remain silent), she would have followed the example of the farmer (who refuses to tell his wife). She disagrees with the rooster&rsquo;s advice, no doubt recognizing it as a critique of her own strategy, the strategy she will use over the course of two and a half years-worth of stories).</p>
	<p>If we consider the entirety of the Nights, this first sample is not a high-profile story, but in Richard Burton&rsquo;s translation it is the occasion for a useful footnote:</p>
	
	<blockquote><p>The Arab word is &lsquo;Taur&rsquo; (Thaur, Saur); in old Persian &lsquo;Tora&rsquo; and Lat. &lsquo;Taurus,&rsquo; a venerable remnant of the days before the &lsquo;Semitic&rsquo; and &lsquo;Aryan&rsquo; families of speech had split into two distinct growths. &lsquo;Taur&rsquo; ends in the Saxon &lsquo;Steor&rsquo; and the English &lsquo;Steer.&rsquo; (29)</p></blockquote>
		
	<p>Not only does Burton commit himself to the claim that Indo-European and Semitic languages are siblings, but he goes out of his way to do it early in the book.</p>
	
	<h3>Two</h3>
	
	<p>Tha is for <em>ithn&acirc;n</em>, &ldquo;two&rdquo; (stem: Th- N - Y). In a form with a <em>ma</em>- prefix, it means something divided into two parts, like a rhymed couplet in poetry, the poetic form called <em>mathnaw&icirc;</em> (accent on the -<em>aw</em>-). It is always a dilemma to transliterate this word for English speakers, since it is a characteristically Persian form, and the Persian pronunciation is almost unrecognizable as the same word: <em>masnav&icirc;</em>, with an accent on the -&icirc;. All long Persian poems are in the <em>masnavi</em> form, for logical reasons. Arabic is so rich in rhymes that monorhyme can last quite a long time, as long as the rhymes hold out. In Persian, as in Turkish or English, with fewer rhymes to work with, the logical solution is the couplet, which requires only two rhyming words per unit. In common language the term <em>Masnavi</em>, used alone, always refers to a particular poem, the <em>Masnavi</em> of that great spiritual master and prolific poet Rumi.</p>
	<p>In one of its substantive forms <em>ithn&acirc;n</em> becomes <em>thanaw&icirc;</em>, a dualist, member of a sect we call Manicheans, who take the universe to have two equal forces pushing things in opposite directions. <em>Al-th&acirc;n&icirc;</em>, &ldquo;second,&rdquo; doesn&rsquo;t just mean &ldquo;second,&rdquo; but, more broadly, &ldquo;the other,&rdquo; something outside our frame of familiarity, potentially a source of conflict. There are a lot of binaries which can organize an argument: center versus periphery, sophisticated culture versus na&iuml;ve one, homeland versus invader, clear vision versus illusion, two partners in a dialogue, two bulls butting heads<strong>.&nbsp;</strong></p>
	<p>There is a famous dispute which has become a cautionary tale for students of the Middle East. The occasion was Edward Said&rsquo;s commentary on an article by the historian Bernard Lewis, &ldquo;Islamic Concepts of Revolution.&rdquo; Lewis&rsquo;s topic is the word <em>thawra</em>, &ldquo;revolution.&rdquo;</p>
	
	<blockquote><p>The root th-w-r in classical Arabic meant to rise up (e.g. of a camel), to be stirred or excited, and hence, especially in Maghribi usage, to rebel. It is often used in the context of establishing a petty, independent sovereignty; thus, for example, the so-called party kings who ruled in eleventh century Spain after the break-up of the Caliphate of Cordova are called <em>thuwwar</em> (sing. <em>tha'ir</em>). The noun <em>thawra </em>at first means excitement, as in the phrase, cited in the Sihah, a standard medieval Arabic dictionary, <em>intazir hatta taskun hadhihi 'lthawra</em>, wait till this excitement dies down &mdash; a very apt recommendation. The verb is used by al-Iji, in the form of <em>thawaran</em> or <em>itharat fitna</em>, stirring up sedition, as one of the dangers which should discourage a man from practising the duty of resistance to bad government. <em>Thawra </em>is the term used by Arabic writers in the nineteenth century for the French Revolution, and by their successors for the approved revolutions, domestic and foreign, of our own time. (Cited in <em>Orientalism</em>, 314-15)</p></blockquote>
	
	<p>Lewis demonstrates the specialist style in all its authority &mdash; the ability to launch philological flights from one realm to another and from one scale to another. And yet proofs by philology are always suspect. Readers of Edward Said&rsquo;s <em>Orientalism</em> may recall that Lewis&rsquo;s philology was a classic case of the western expert refusing to take Arab history seriously. Said&rsquo;s comment is chastening. It could apply to a lot of us: &ldquo;At no point in the essay is one sure where all these terms are supposed to be taking place except somewhere in the history of words&rdquo; (314).</p>
	
	<blockquote><p>The entire passage is full of condescension and bad faith. Why introduce the idea of a camel rising as an etymological root for modern Arab revolution except as a clever way of discrediting the modern? Lewis&rsquo;s reason is patently to bring down revolution from its contemporary valuation to nothing more noble (or beautiful) than a camel about to raise itself from the ground. Revolution is excitement, sedition, setting up a petty sovereignty &mdash; nothing more. (315)</p></blockquote>
	
	<p>This confrontation is a formidable and influential political conflict, but it&rsquo;s also a meeting between two different modes of proof, or a thesis being stalked by its antithesis. Both claim actual evidence, and this makes it something more like a real debate. If Lewis&rsquo;s argument is a Seurat <em>pointilliste</em> landscape, Said takes us close up to show the missing spaces.</p>
	<p>Lewis&rsquo;s argument moves from one Arab commentator to another, collecting words for change of government which might be translated as &ldquo;revolution.&rdquo; (If the words for revolution are static and cyclical at the verbal level, it seems to say, let&rsquo;s just assume that deeds follow the etymologies.) His first choice is <em>dawla</em>: &ldquo;The basic meaning of the root <em>d-w-l</em>, which also occurs in other Semitic languages, is to turn or to alternate &mdash; as for example in the Qur&rsquo;anic verses &lsquo;These [happy and unhappy] days, we cause them to alternate (<em>nudawiluha</em>) among men&rsquo; (Qur&rsquo;an III, 134/140)&hellip;&rdquo; (Lewis, &ldquo;Islamic Concepts of Revolution,&rdquo; 30). The thrust of his essay is to sketch a characteristic quietist attitude towards misrule in which change of governments is, etymologically, repetitive and arbitrary. &ldquo;The Western doctrine of the right to resist bad government,&rdquo; he adds, &ldquo;is alien to Islamic thought&rdquo; (33). It assumes, as a European norm, that revolution is standard equipment, a button on the western dashboard, a political ejection seat on all standard European models of government.</p>
	<p>The comparison has a logical flaw. We can educe as many oppositional or revolutionary movements in one culture as in the other. The use of D-W-L as evidence of a static culture would be a stronger argument if the western term &ldquo;revolution,&rdquo; from <em>volvere</em>, to roll over, did not have an etymology just like its Arabic counterpart, D-W-L.</p>

	<div class="illo"><img src="../_img/tha-4.png" width="600" /></div>

	<h3>Lonely Bull</h3>
	
	<p><em>Kal&icirc;la wa Dimna</em> is composed of a series of framing tales. The first is a sad, long narrative, the saddest character being a <em>thawr</em>, which pairs one character with another in an extended dialogue.</p>
	<p>The story is widely distributed. A Sanskrit version is particularly old. And then it moves west. The plots remain more or less the same. The languages differ, along with the style. The translator into Arabic, Ibn al-Muqaffa&lsquo;, was a Persian intellectual who rose to a position of influence in the early days of the Abb&acirc;sid caliphate as a translator from Greek and Middle Persian, a writer of refinement, one of the men of letters who set the mold for Arabic prose style. Some of his spoken witticisms remain (he would greet a courtier with a prominent nose, one Sufy&acirc;n ibn Mu&rsquo;&acirc;wiya al-Muhallab&icirc;, saying &ldquo;How are the two of you?&rdquo; &mdash;Arberry 73), but, beyond anecdotes, <em>Kal&icirc;la wa Dimna</em> is his one extant complete work. This means that all we can see of his role in the history of Arabic prose is a collection of stories about hierarchy and power, rooted in pre-Islamic Iran and further east in India. They would have been enough to establish his reputation if he had written nothing else. E.G. Browne, judicious in so many things, regrets that <em>Kal&icirc;la wa Dimna</em> was the only surviving text (<em>Literary History</em> 1.76), but it is hard to agree with him.</p>
	<p>The source Ibn al-Muqaffa&rsquo; used was a sixth-century Middle Persian text, now lost, which traces back to more than one text in Sanskrit, notably the (extant) <em>Panchatantra</em>, the five <em>tantra</em>s. (You can hear the similarity between Persian <em>panj</em>, &ldquo;five,&rdquo; and Sanskrit &ldquo;Pancha.&rdquo; Or for that matter, the <em>penta</em> of Pentateuch, Greek for the five scrolls, i.e. Genesis, Exodus, Leviticus, Numbers and Deuteronomy.) There are a lot of translations whose origin is the <em>Panchatantra</em>. Its progeny is everywhere. (It reached English literature in 1570 in a translation, from Italian, by Sir Thomas North.)</p>
	<p>The premise of moral parables is that they contain truths which are universal and unchanging, <em>th&acirc;bit</em>. The will to express them as profound truths is a constant, but parables and proverbs also contradict one another (many hands make light work but too many cooks spoil the broth). The term for moral parables in Arabic is a derivation of the verb <em>mathala</em> (M-Th-L), to resemble, to compare. A noun form, <em>mathal</em> (plural <em>imth&acirc;l</em>) means a likeness, example, parable or proverb, the constituent material of <em>Kal&icirc;la wa Dimna</em>. In <em>Kal&icirc;la wa Dimna</em>, as in the <em>1001 Nights,</em> the stories are told to a king, Dabshal&icirc;m of India, by the philosopher Baydab&acirc; (Bidpa, Arabic Baydb&acirc;). Unlike the <em>Nights</em>, there is no threat to the storyteller. Dabshal&icirc;m just asks for stories (there are five requests), ordering up a particular moral, and Bidpa answers, not with the businesslike forward motion of the Nights, but with a series of leisurely meanders from one story to the next. Dabshal&icirc;m&rsquo;s first request, which gives the book its title, is for a story in which two friends have a disastrous falling out because of calumny and treachery.</p>
	<p>Bidpa&rsquo;s long, wandering answer, is patched together with little ingenious stories ranged in debate formation, one answering the other. It starts slowly. First we hear a father&rsquo;s advice to his oldest son (we hear it at tiresome length), encouraging him to seek his fortune. The son yokes up two oxen (<em>thawr&acirc;n</em>), the narrator names them (Bandaba and Shatraba), Shatraba gets stuck in the mud, and the humans leave him behind. Once abandoned, or liberated, we forget the humans and Shatraba becomes the hero of the tale. Shatraba is the bull whose story will be sad, but we see him up close for the first time alone, against the backdrop of the natural scene. In A.J. Arberry&rsquo;s translation:</p>
	
	<blockquote><p>Presently he came to a broad meadow adorned with all manner of succulent grasses and aromatic herbs, such as the Garden of Eden itself would have bit the finger of envy to behold, and Paradise looked on with eyes wide open, in amazed stupefaction. Shatraba approached it heartily and stayed there for quite a while&hellip;. It was not long before he became fat and prosperous. (76)</p></blockquote>
	
	<p>Shatraba&rsquo;s bellows of pleasure waft across to a nearby animal community, and there we are introduced to their king (a lion) and two jackals, the title characters. Once we have met Kalila and Dimna, all the threads are in place on which the fables will be hung. They argue with one <em>mathal</em> after another.</p>
	<p>Dimna is the heavy, the Machiavellian manipulator who notices the lion&rsquo;s fear at the sound of the bull&rsquo;s voice. If Dimna himself embodies a moral, it&rsquo;s a pretty simple one: some characters are just no good. Dimna wants to gain power by using the king&rsquo;s fear against him, so after an exchange of tales with Kalila, debating where his scheme is worth doing, Dimna goes to interview the ox himself and ends up introducing him to the lion. Lion and ox become friends, Dimna manages to establish discord between them. The result will be combat. (A disastrous falling out was, remember, king Dabshal&icirc;m&rsquo;s assignment). Perhaps the moral is that, when you tell a story, you should tell the one your ruler wants to hear.</p>
	<p>The sad turning point of the story takes place when the friendship of the lion and the ox, which would have been logical as the end of the story, is broken. Dimna argues to the lion that someone so strong as the <em>thawr</em> is dangerous just for his strength, so the only proper response is a pre-emptive strike. The lion kills the ox (another not illogical place to end the story) but he regrets it &mdash; and in a kind of epilogue Dimna is put in <em>wath&acirc;qa</em>, shackles, and thrown in prison (apparently animals have chains and a prison) where he dies of hunger. It satisfies our desire for justice, but not our taste for closure. There is never really a climax to the story, even if a bull gets sacrificed. In fact we never actually see the battle between lion and ox; it takes place offstage.</p>
	
	<h3>And Then</h3>
	
	<p>The Tha word <em>thumma</em>, roughly &ldquo;and then,&rdquo; is ubiquitous in narrative. <em>Kal&icirc;la wa Dimna </em>is seasoned with it at almost every line, &ldquo;and then&hellip; and then&hellip;&rdquo; It&rsquo;s a prose rhythm that can suggest just one damn thing after another, like the fabric of history, before we have added a mechanism of cause and effect. It&rsquo;s not rare to hear that paratactic narratives, the ones which take the connections for granted and leave them unstated, are na&iuml;ve and simple, an early style of story-telling waiting to be outgrown. You sometimes hear the same thing about lyric poetry in Persian, the <em>ghazal</em>, that the connections between one verse and the next are arbitrary, that Persian esthetics produces not so much a unified poem as a collection of disconnected parts. William Jones, in his 1772 &ldquo;Translations from the Asiatick Languages,&rdquo; famously called them &ldquo;orient pearls at random strung.&rdquo; You often hear readers of Persian poetry prove that those poems do in fact have unifying elements &mdash; usually by the discovery of repeated images or moral themes. It doesn&rsquo;t seem to matter much, but if the argument lasts long enough we might come up with a convincing definition of &ldquo;unity.&rdquo; It is not our problem.</p>
	<p>The stem Th-Q-B is to pierce, to bore, to drill a hole. Threading a pearl is an image of accomplishing a difficult task. As an active participle it is <em>th&acirc;qib</em>: a word applied to an unnamed star, in a mysterious sura of the Qur&rsquo;&acirc;n (86.1-4). <em>Al-najm al-th&acirc;qib</em>, the star which pierces.</p>
	<p>Tha is also for <em>tham&acirc;na</em>, the number eight. Inside the constellation Thawra is the faint cluster of eight little stars, eight at least to the sharp sighted. For most observers it is seven. In Persian its name is Parvin. In Arabic it is <em>Thurayya.</em> You find it in English as the name Soraya. Thurayy&acirc; is a beautiful fuzzy object, not particularly bright or piercing, though a name for it in India is The Razor.</p>
	<p>The stem of the name <em>thurayy&acirc;</em> seems to be <em>tharan</em>, earth or soil, giving rise to the proverb</p>

	<blockquote>
	<p>&#1575;&#1740;&#1606; &#1575;&#1604;&#1579;&#1585;&#1740; &#1605;&#1606; &#1575;&#1604;&#1579;&#1585;&#1740;&#1575;</p>
	<p><em>Aina al-tharan min al-Thurayy&acirc;</em></p>
	<p>What has the earth to do with the Pleiades?</p>
	</blockquote>

	<p>&mdash;which suggests that similarities of sound are an undependable index of meaning, or perhaps that common etymologies not infrequently contain opposites. A proverb arguing against proof by etymology.</p>
	<p>One of the most famous poems of Hafez, the one addressed to the pale woman from Shiraz, concludes with a vision of the Pleiades. It is standard for a poet in the last <em>bayt </em>of a ghazal to stand away from the poem and speak in the second person as if in dialogue with a mirror. Hafez congratulates himself for having accomplished a great poem:</p>
	
	<blockquote>
	<p>
		&#1594;&#1586;&#1604; &#1711;&#1601;&#1578;&#1740; &#1608; &#1583;&#1585; &#1587;&#1601;&#1578;&#1740; &#1576;&#1740;&#1575; &#1608; &#1582;&#1608;&#1588; &#1576;&#1582;&#1608;&#1575;&#1606; &#1581;&#1575;&#1601;&#1592;<br>
		&#1705;&#1607; &#1576;&#1585; &#1606;&#1592;&#1605; &#1578;&#1608; &#1575;&#1601;&#1588;&#1575;&#1606;&#1583; &#1601;&#1604;&#1705; &#1593;&#1602;&#1583; &#1579;&#1585;&#1740;&#1575; &#1585;&#1575;
	</p>
	<p>
		<em>Ghazal gofti-o dorr softi; biy&acirc; wa khowsh bekh&acirc;n H&acirc;fez;</em><br>
		<em>Ke bar nazm-e tow efsh&acirc;nad falak &lsquo;eqd-e </em><em>S</em><em>orayy&acirc;-r&acirc;</em>
	</p>
	<p>[&ldquo;You&rsquo;ve spoken a <em>ghazal</em>, you&rsquo;ve threaded pearls (<em>softan</em> is the Persian equivalent of Arabic <em>thaqaba</em>); come here / go ahead and sing it beautifully, Hafez, so beautifully that over your verse the heavens (<em>falak</em>) will scatter the necklace of Soraya.&rdquo; In Dick Davis&rsquo;s translation:</p>
	
	<p>Hafez, your poem&rsquo;s written now,<br>
	&nbsp; The pearl you&rsquo;ve pierced is poetry&rsquo;s;<br>
	Sing sweetly &ndash; heaven grants your verse<br>
	&nbsp; The necklace of the Pleiades.]</p>
	</blockquote>
		
	<p>It is a famous poem, famous among English fans of Hafez as a touchstone. This verse was the occasion William Jones, in his translation, used to exemplify his claim of randomness, as if to make Hafez say &ldquo;yes, my verses are what you say they are, an unordered sequence&rdquo;:</p>
	
	<blockquote>
	<p>Go boldly forth, my simple lay,<br>
	Whose accents flow with artless ease,<br>
	Like orient pearls at random strung&hellip;</p>
	</blockquote>
		
	<p>It&rsquo;s a loose translation, and the Pleiades are absent from it, but there is something beautiful in watching Jones reconfigure the poem to make his own point. In Persian, the balance between pearls and Pleiades is complicated: Hafez praises himself for having pierced pearls and strung them together for a necklace. His reward is to have the sky offer him the Pleiades, or rather to &ldquo;scatter&rdquo; them (<em>afsh&acirc;nad</em>). The Pleiades are a necklace, <em>&lsquo;aqd-e Surayy&acirc;</em> (Thurayy&acirc;). I don&rsquo;t know a great deal about Hafez, but I can attest that the conclusion is beautiful: Hafez strings the pearls together and the sky sends them back disconnected, in the form of stars. So in the two metaphors for esthetic success, one comes from the crafts &mdash; piercing a hole in the round surface of a pearl; this is the work accomplished. The other comes from the sky, bringing Thurayy&acirc; to earth as a reward. One is an act of putting a necklace together, the other an act of taking one apart.</p>



	<div class="illo"><img src="../_img/tha-5a.png" width="600" /></div>

	<br/><br/>
	
	<h4>Up next...</h4>

	<div id="letters">
		<a class="live" href="/the-arabic-alphabet/jim/">
			<div class="letter">
				<div class="symbol">&#1580;</div>
				<div class="english"><span>A Letter Called Jim</span></div>
			</div>
		</a>
	</div>
	
</article>
<cfinclude template="../_footer.cfm">

