<cfset chapter = "Sin"><cfinclude template="../_header.cfm">

<article>

	<h1><a href="/">The Arabic Alphabet: A Guided Tour</a></h1>
	<h4>by Michael Beard</h4>
	<h5>illustrated by Houman Mortazavi</h5>
		
	<div class="illo"><img src="../_img/sin-01a.png" alt="Sin" /></div>
	<h2>S&icirc;n is for Zenith</h2>
	
<p class="first">The sound of S&icirc;n (pronounced &ldquo;scene&rdquo;) is the clear sibilant we represent with our letter S. The S we know is all curves. S&icirc;n is usually more angular, a little closer to the W shape of its Phoenician ancestor. Greek Sigma comes from the same source, the W shape tipped up 90 degrees clockwise.There was a Nabatean predecessor of S&icirc;n in the form of a bowl shape with an upright growing out of it, something like Hebrew Shin. The shape of S&icirc;n grows out of it: two miniature half-circles resting side by side. What strikes the eye are those three short uprights, referred to as &ldquo;teeth&rdquo; (S&icirc;n word <em>sin&acirc;n</em> in Arabic, the plural of <em>sinn</em>). It is not my job to say what is beautiful and what isn&rsquo;t, but what I&rsquo;m taken by in the most elegant handwritten S&icirc;n is a slight asymmetry: the space between the first two teeth (reading right to left) is slightly narrower than the space between the second and third.&nbsp;</p>
<p>In terminal form S&icirc;n ends with a rounded clockwise sweep, a shape which fledgling calligraphers struggle over, the clockwise descent and return, thickening along the bottom, tapering to a point as it rises on the left. The same curve reappears in Shin, &#7778;ad &amp; &#7692;ad.&nbsp;</p>
<p>S&icirc;n went through a period in its evolution when it had a triangle of dots suspended below the line, to distinguish it from the letter Sh&icirc;n, the next in sequence, which has three dots above. (Sh&icirc;n kept them. Present-day S&icirc;n goes commando.) A streamlined variant of S&icirc;n, still used, was developed in interests of efficiency: it can take the form, perhaps as a visual representation of the smooth prolonged sound of sibilance, of a straight unrippled line, often descending slightly<strong>,</strong> throwing the base line down a notch and continuing at a lower level. Easiest letter ever. In the initial or medial position the line simply continues on for a bit with nothing else happening.</p>
<p>The source of <em>sinn</em>, &ldquo;tooth,&rdquo; is the Arabic stem S&ndash;N&ndash;N, which, as a verb, means to sharpen, mold, shape<strong>.</strong> In one form, <em>sunna</em>, it means, in Hans Wehr&rsquo;s definition, &ldquo;habitual practice, customary procedure or action, norm, usage sanctioned by tradition; <em>al-sunna</em> or <em>sunnat al-nab&icirc;y</em>, the Sunna of the Prophet (<em>nab&icirc;y</em>), i.e. his sayings and doings, later established as legally binding precedents...&rdquo; In other words, the <em>ahl-al-sunna</em> are the follows of the <em>sunna</em>, in English &ldquo;Sunnis.&rdquo; It&rsquo;s an admirable definition, if only because Wehr defines the etymological stream of meanings without getting excited, or lost in detail. A history book, once it has said &ldquo;Sunni,&rdquo; has to go into teacher&rsquo;s mode, including the actors and the theology, plus the alternative, Shiism, and to describe how Shiism ended up breaking away from &ldquo;Sunnism.&rdquo; Today everyone knows it, or can look it up, and the history hardly seems necessary. Hans Wehr defines <em>sh&icirc;&lsquo;a</em>, the other major branch, as &ldquo;followers, adherents, disciples, faction, party, sect&rdquo;; <em>al-sh&icirc;&lsquo;a</em>, the faction of Ali, the Shiah, the Shiites (that branch of the Muslims who recognize Ali, the Prophet&rsquo;s son-in-law, as the rightful successor.)&rdquo; It&rsquo;s all the definition you need. They&rsquo;re just words, ordinary words. Neither<em> sunna</em> nor <em>sh&icirc;&lsquo;a</em> occur in the Qur&rsquo;&acirc;n.</p>
<h3>Literacy&nbsp;</h3>
<p>&rdquo;Literacy&rdquo; in Persian is <strong>&#1587;&#1608;&#1575;&#1583;</strong>, <em>sav&acirc;d</em>. <em>B&acirc; sav&acirc;d</em> is &ldquo;literate.&rdquo; The origin is the Arabic adjective <em>&lsquo;asw&acirc;d</em> (fem. <em>sawd&acirc;</em>&rsquo;), from <em>sawwada</em>, &ldquo;to blacken, color black,&rdquo; also &ldquo;to scribble&rdquo; (i.e. to fill a page with ink). As A&#7717;mad F&acirc;ris Al-Shidy&acirc;q observes, in the opening to his beautiful compendium of anecdotes, digressions, advice,obscure etymologies and lists, <em>Al-S&acirc;q &lsquo;al&acirc; al-s&acirc;q</em> (Leg over leg, 1855 <strong>&#1575;&#1604;&#1587;&#1575;&#1602; &#1593;&#1604;&#1740; &#1587;&#1575;&#1602;</strong>), &ldquo;There can be no harm in following in the footsteps of men who have rendered their reputations white by covering pages in black" (trans. Humphrey Davies, 23).</p>
<p>In one way literacy is a condition like being unique: there aren&rsquo;t degrees of it. In another way, there are degrees of literacy which can increase in steps. We can regard erudition as intensified literacy. Anyone who writes, strictly speaking, has <em>sav&acirc;d</em>, but there are writers who make a point of being &ldquo;more&rdquo; literate, weaving their erudition into the story.&nbsp;</p>
<p><em>Boussole </em>(Compass) is a 2015 novel by Mathias &Eacute;nard, about a musicologist specializing in the Middle East, is as erudite as they come. (This may or may not be the reason it won the Goncourt prize.) The hero&rsquo;s subject of concentration, relations between the histories of Turkish music and European music, is a bigger and more varied subject than the uninitiated observer might guess (e.g. Liszt&rsquo;s journey to Istanbul to perform for Sultan Abd&uuml;lmecid in 1847, the career of Gaetano Donizetti, older brother of the Italian composer Giuseppe Donizetti, who was hired by the same sultan to tutor the Turkish military bands, Mozart&rsquo;s &ldquo;Rondo alla Turca,&rdquo; Abd&uuml;lmecid&rsquo;s taste for &ldquo;Marriage of Figaro&rdquo; and his dissatisfaction with the royal performance). It&rsquo;s a subject rich in examples, but he observes that it falls &ldquo;into a scientific void, a hole&rdquo; (82). It isn&rsquo;t clear whether a gap in academic knowledge is a good thing, because it leaves space for new research, or a bad one because it&rsquo;s the kind of gap in the academic framework which makes us ask &ldquo;where do you put it?&rdquo; The stuff the novel is made of is the content of his research, the anecdotes, etymologies, composite works of anecdotes which overflow the specialty.</p>
<blockquote>
<p>Bosnian folklore includes traditional songs called <em>sevdalinke</em>. The name comes from a Turkish word, <em>sevdah</em>, borrowed from Arabic <em>sawda</em>, which means &ldquo;the black mood.&rdquo; In Avicenna&rsquo;s Canon of Medicine, it&rsquo;s the name for the dark mood, the <em>melan kholia</em> of the Greeks, melancholy. (426)</p>
</blockquote>
<p>So <em>sevdah</em> is a synonym for <em>h&uuml;z&uuml;n</em>, the word Orhan Pamuk used for melancholy in his memoir <em>Istanbul</em>.</p>
<blockquote>
<p>So it&rsquo;s the Bosnian equivalent for the Portuguese word <em>saudade</em>, which (unlike what the etymologists assert) also comes from the Arabic <em>sawda </em>&mdash; and from the same black bile. <em>Sevdalinke</em> are the expression of melancholy, like fados. The melodies and the accompaniment are a Balkan version of Ottoman music.</p>
</blockquote>
<p>He appends to the etymologies a story, the plot of a particular Sevdalinka called <em>Kraj tanana &scaron;adrvana</em>. (The story is minimal, as narratives go, really just a container for a mood. A slave is in love with the Sultan&rsquo;s daughter. She asks him his name and where he is from. He replies that he is from Yemen, the tribe of Asra, where when people fall in love they die.)</p>
<blockquote>
<p>The text of this song with the Turkish-Arab motif is not, as one might think, an old poem from the Ottoman era. It&rsquo;s a work by Safvet-beg Ba&scaron;agi&#263; &mdash; a translation of a famous poem by Heinrich Heine, &ldquo;Der Asra.&rdquo;</p>
</blockquote>
<p>One will find in<em> Compass</em>, if my count is correct, approximately an anecdote per page (depending how you count) &mdash; not so many as in <em>Leg Over Leg,</em> but still a respectable density of surprising information. It could be an encyclopedia of words and cultural oddities which straddle the Islamic world and Europe. The list is so formidable that you wonder why &Eacute;nard bothered to add a plot.</p>
<p>There is a mystery in the stem S&ndash;W&ndash;D: by a linguistic process I don&rsquo;t really understand, the W can become a Y (or an A). This is why <em>sayyid</em> (fem. <em>sayyida</em>), &ldquo;master,&rdquo; &ldquo;gentleman,&rdquo; and more recently just &ldquo;mister,&rdquo; may come from the same stem. You can see the logic: if blackness is linked with literacy and dignity, it&rsquo;s a positive image. It can also, in Iran particularly, be a title for people who can trace their ancestry back to the Prophet. It can also be a different stem.</p>
<h3>Solomon</h3>
<p>There is a S&icirc;n word which brings us closer to universals of Islam in the physical act of prayer: S&ndash;J&ndash;D, to bow down, in this case to bow towards a central point, a physical image of devotion. A <em>saj&acirc;da</em> is a surface upon which one bows, a prayer rug. A <em>masjid</em>, anglicized as &ldquo;mosque&rdquo; (we borrowed it from French), is a place where S&ndash;J&ndash;D takes place, a place whose purpose is to encourage the act of centering. One of the earliest suras to be sent down, Sura 96, <em>&lsquo;Alaq</em>, &ldquo;The drop of blood,&rdquo; ends with a beautiful compressed imperative: <em>asjud wa iqtarib</em>, &ldquo;bow down and come near&rdquo; (Q 96.19). The juxtaposition of verbs (<em>asjud</em>, &ldquo;bow&rdquo; and <em>iqtarib</em>, &ldquo;come closer&rdquo;) is not quite a pun but it is a subtle echo of images, since bowing down does bring a person closer, not just internally but physically as the body inclines toward the focal point.&nbsp;</p>
<p class="illo"><img src="../_img/sin-02.png" width="300" align="right" style="margin-right:-80px" /></p>
<p>The prophet Samuel is peripheral to Islamic traditional history, referred to but not named in the Qur&rsquo;&acirc;n (Q 2.246). There is a prophet named <strong>&#1740;&#1575;&#1605;</strong>, S&acirc;m, whose name looks a little as if he might be our Samuel. But S&acirc;m is someone else, the son of Noah whose name we know as Shem. (There is also, in Persian, a hero in the <em>Sh&acirc;hn&acirc;meh</em> named S&acirc;m, the father of Rostam. No connection.) &nbsp;Shem is the father of the people we call &ldquo;Semitic.&rdquo; The descendants of S&acirc;m are called S&acirc;m&icirc;. A bigger claim to the eminence of Noah&rsquo;s son, seen for some perspectives (bigger than his role as a prophet, which is not universally acknowledged in any event), is his role as father of the language group (Semitic) which includes (for example) Amharic, Aramaic, Assyrian, Arabic and Hebrew.</p>
<p>The ranking S&icirc;n prophet is Sulayman, the Solomon of the Old Testament (whose name is derived from a Hebrew version of the Arabic root S&ndash;L&ndash;M, to be unharmed, free, peaceful, as in Arabic <em>Isl&acirc;m</em>, <em>muslim</em> and <em>sal&acirc;m</em>, cognate with Hebrew <em>shalom</em>, as Shel&ocirc;m&ocirc; is cognate with Solomon). You find the same stem in western place names like Salem and the last two syllables of Jerusalem<strong>.</strong></p>
<p>Sab&acirc;&rsquo; is the region called Sheba in Hebrew (now identified as somewhere in Yemen). There is a sura in the Qur&rsquo;&acirc;n by that name (Sura 34) which describes (in passing) its destruction by <em>sayl</em> (flood). Sulayman&rsquo;s death is described in the same sura. It is a picture of immobilization. No one is aware that he isn&rsquo;t with them any longer because they think he is simply standing motionless, leaning on his cane (Q 34.14).Even the <em>jun&ucirc;n</em>, the jinns, don&rsquo;t know he&rsquo;s dead until his cane has been eaten away by some little animal, a <em>da&rsquo;abba</em>. (I began to write &ldquo;insects&rdquo;: a friend suggests &ldquo;termites.&rdquo;) Most translators have shied away. There are also &ldquo;the beast of the earth&rdquo; (A.J. Arberry), &ldquo;a creeping creature of the earth&rdquo; (Mohammed Marmaduke Pickthall), &ldquo;a worm&rdquo; (N.J. Dawood), &ldquo;un animale della terra&rdquo; (Alessandro Bausani), &ldquo;un reptile de la terre&rdquo; (Kasimirsky). And then he collapses to the floor. His authority outlives him until his death is known.</p>
<p>Wealth, that other possession that outlives its owner, has a function in literature, which is to be despised. Ab&ucirc; Zayd of Ser&ucirc;j in Al-&#7716;ar&icirc;r&icirc;&rsquo;s <em>Maq&acirc;m&acirc;t</em> can both praise or attack it indiscriminately, but, more frequently, once money is invited into a story it can expect nothing but abuse. In Persian as in English the usual representation of wealth is gold and silver. There are many ways to make the claim that we are above taking wealth seriously. The great 12th-century Persian poet Ni&#7827;&acirc;mi Ganjavi (best known for his version of the Layla and Majn&ucirc;n story, the one that inspired Eric Clapton&rsquo;s &ldquo;Layla&rdquo;), in the introduction to his other great story, the Seven Portraits (<em>Haft paykar</em>), expresses his distaste for gold alphabetically. The late Julie Meisami, in her brilliant translation of the poem, comes as close as English can get::</p>
<blockquote>
<p>&lsquo;Tis wrong gold makes your eyes shine bright,<br />for wisdom&rsquo;s the world&rsquo;s true delight.<br />&ldquo;Gold&rdquo; is two letters unconnected;<br />how should you boast of something scattered? (p. 26)</p>
</blockquote>
<p>&ldquo;Gold&rdquo; is <strong>&#1586;&#1585;</strong>, <em>zar</em>. The letters are unconnected because the Za and the Ra stand alone, i.e. because Za doesn&rsquo;t connect on the left. (Actually, neither one connects on the left.) The insult is that gold looks insubstantial when written on the page. <strong>&#1586;&#1585;</strong> just doesn&rsquo;t look like much. Silver is <em>s&icirc;m</em> (&#1587;&#1740;&#1605;), a venerable Indo-European word which can be traced back to Greek &#7940;&sigma;&eta;&mu;&omicron;&sigmaf;, <em>as&ecirc;mos</em>). <em>S&icirc;m</em> is insubstantial in different way. Its spelling allows Niz&acirc;mi to launch another alphabetical insult, a bit more elaborate because it requires you to know that brass is <strong>&#1605;&#1587;,</strong> <em>mes</em> (also transcribed &ldquo;mess,&rdquo; or &ldquo;miss&rdquo; with a double letter to show it&rsquo;s a clear S sound):</p>
<blockquote>
<p><strong>&#1587;&#1740;&#1605; &#1576;&#1740; &#1740;&#1575; &#1586; &#1605;&#1587; &#1606;&#1605;&#1608;&#1606;&#1607; &#1576;&#1608;&#1583;<br /></strong><strong>&#1582;&#1575;&#1589;&#1607; &#1570;&#1606;&#1711;&#1607; &#1705;&#1607; &#1576;&#1575;&#1688;&#1711;&#1608;&#1606;&#1607; &#1576;&#1608;&#1583;</strong></p>
<p>S&icirc;m without <em>y&acirc;</em> is <em>miss</em> (that&rsquo;s brass)<br />Especially when they&rsquo;re reversed. (p. 26)</p>
</blockquote>
<p>So silver (<em>s&icirc;m</em>) is S&icirc;n-Y&acirc;-Mim. The pun requires us to take out the middle letter (leaving S&icirc;n and Mim) and reverse what&rsquo;s left. So <strong>&#1587;&#1740;&#1605;</strong> becomes <strong>&#1605;&#1587;</strong>. As insults go, Niz&acirc;mi had to work for this one, and produced a translator&rsquo;s dilemma in the process.</p>
<p>The word <em>ra&rsquo;s</em> (<strong>&#1585;&#1571;&#1587;</strong>) in Arabic, &ldquo;head,&rdquo; is in Persian <em>sar </em>(<strong>&#1587;&#1585;</strong>). The symmetry of sounds may seem at first glance uncanny, as if they were mirror images of one another, but the resemblance is less striking seen from close up, because <em>ra&rsquo;s</em> is a three-letter word, the addition being that catch of the voice called Hamza. There is one similarity at least: both are used in metaphors of authority, power and status. Arabic <em>ra&rsquo;s</em> gives you <em>ra&rsquo;&icirc;s</em>, a boss, chief, or president. <em>Ra&rsquo;&acirc;sa</em> is leadership. Persian <em>sar </em>&nbsp;gives you <em>sar-d&acirc;r</em>, a leader or chief. In Persian a <em>sarpasb&acirc;n</em> is a police officer. A <em>sar-jukheh</em> is corporal. <em>Sar-afr&acirc;z</em> means honored or exalted.</p>
<p class="illo"><img src="../_img/sin-04.png" width="450" /></p>
<p>Sin words of authority are not limited to the word <em>sar</em>, or the root S-&rsquo;-R. In Persian there is that word with the puzzling tri-consonant root, a <em>sayyed</em>. Arabic s<em>ul&#7789;a</em> (<strong>&#1587;&#1604;&#1591;&#1577;</strong>) is authority. With an <em>&acirc;n-</em> suffix it occurs in the Qur&rsquo;&acirc;n as an abstract term for power, <em>sul&#7789;&acirc;n</em>, later the term for a person who occupies a position of power, a sultan. The exercise of authority is S&icirc;n word <em>siy&acirc;sa</em>, politics.</p>
<p><em>Siy&acirc;sa</em>, politics is, we often say, unavoidable. Politics is everywhere, always, even when invisible, like radio waves or gravity. The attempt to avoid politics, in a familiar paradox, is a political act. Once we become aware of this, it follows that there are two possible reactions: one is to acknowledge it, in order to track down the unacknowledged political currents which shape what we do. The other reaction is denial. Still, the deniers, those who imagine themselves innocent, participate in unacknowledged systems of power. An inquiry into the alphabet is no exception. Literacy and language are political issues. So is the choice of scripts (Arabic or Devanagri in India, Arabic or Roman in Turkey). The alphabet intersects with the consequential moments in history. The calligrapher Y&acirc;qut Al-Mustasim&icirc; survived Hulagu&rsquo;s sack of Baghdad, in 1258 CE, by hiding out in a mosque. Perhaps it matters that Timothy Matlack wrote the Declaration of Independence, Jacob Shallus wrote the American constitution.&nbsp;</p>
<p class="illo"><img src="../_img/sin-05.png" width="300" align="right" style="margin-right:-80px" /></p>
<p>The earliest Qur&rsquo;&acirc;nic encounter we have with the living Sulayman (Q 27.15-44) is not the account of his death, but an account of the days when his power was at its greatest. His authority is not<em> siy&acirc;sa</em> in the usual sense, not the predictable power of inheritance or usurpation, but something linguistic. The Lord, we learn in Sura 27 (<em>Surat al-Naml</em>, the sura of the ant), has granted him &lsquo;<em>ilm</em>, &ldquo;knowledge,&rdquo; in this case knowledge synonymous with power. Famously, he tells his people &ldquo;I have been taught <em>man&#7789;aq al-&#7789;ayr,</em> the language of the birds&rdquo; (27.16), and presumably the dialects of all creation. In the opening episode all living creation has been assembled before him, in rows, perhaps in the pattern of subjects gathered around a central point. We see a representative list of them: jinns, humans, birds. It includes insects. In fact, when the account begins, we are shown his world from the point of view at ground-level, through insect eyes &mdash; the ants, <em>naml</em> (pl. <em>nim&acirc;l</em>), who give the sura its name. One ant says to another to get out of the way. The passersby will trample us. Sulaym&acirc;n smiles when he hears it, and moves on to further business.</p>
<p>The <em>hudhud</em> arrives late, and Sulaym&acirc;n threatens him with death unless <em>la-y&acirc;t&rsquo;&icirc;n&icirc; bi-</em><strong><em>sul&#7789;&acirc;nin </em></strong><em>mub&icirc;nin</em>, unless he can show a good reason (27.21). A <em>sul&#7789;&acirc;n mub&icirc;n</em> is an evident, clear, unmistakable authority. <em>Sul&#7789;a</em> is in this case is the authority of a proof. The <em>hudhud</em> in fact has a convincing reason. He has discovered that Sulaym&acirc;n&rsquo;s authority is incomplete because there is a dominion out there unaware of his power, a place where they still worship the sun, a religion which <em>lahum fasaddahum &lsquo;an al-sab&icirc;l</em>, &ldquo;led them away from the <em>sab&icirc;l</em>--the right path&rdquo; (27.24). The nation still outside Sulaym&acirc;n&rsquo;s <em>Sul&#7789;a </em>is Sab&acirc; (which would later be destroyed by flood). Its ruler is an unnamed woman. (Later tradition calls her Bilq&icirc;s.) There is an inexplicable interlude in which a <em>jinn </em>delivers her to Sulayman and alters the throne room; he has paved its floor with glass. When she arrives at Sulaym&acirc;n&rsquo;s court she reaches the glass and thinks it is the surface of a lake, or a pond. She lifts her dress to walk across and shows her <em>s&acirc;q</em>, her legs (27.44). Sulaym&acirc;n explains that the flat surface which seems to be water is slabs of glass.</p>
<p>The story is not self-explanatory. It is a conundrum which may have a mystical explanation which I don&rsquo;t get. In its large outlines the story of Sulaym&acirc;n is a straightforward, symmetrical narrative: the story opens with the discovery that his power is one piece short; it concludes with that gap being filled in. It even has the outline of a romance. But so much is untold. Sulaym&acirc;n for some reason has her throne magically brought to him before she arrives. He alters it in some unexplained way. She recognizes it. Why should it conclude with a glimpse of the queen&rsquo;s legs? Does it hint at the inevitable erotic relationship between the queen and Sulaym&acirc;n? Is it to humiliate her? To show his power? We don&rsquo;t know why the floor is glass; we don&rsquo;t even know how she got there. It is crucial to the narrative that she arrives, but the trip is not part of the story. It is a voyage, but an unseen voyage from periphery to center.</p>
<p class="illo"><img src="../_img/sin-06.png" width="650" /></p>
<h3>Safari</h3>
<p>A journey is a <em>safar</em> in Arabic, Persian and Urdu. In the form &ldquo;safari&rdquo; it&rsquo;s an English word too, though it hasn&rsquo;t been one for long. (It doesn&rsquo;t make it into the OED until the 1933 supplement.) It doesn&rsquo;t come to English directly from Arabic, but through the intermediary of Swahili, the Bantu-based language of the <strong>&#1587;&#1575;&#1581;&#1604;</strong> (<em>S&acirc;&#7717;il</em>), a S&icirc;n word (borrowed from Arabic) for coast, plural <em>saw&acirc;&#7717;il</em>. (Richard Burton translates <em>Saw&aacute;&#7717;&iacute;l&iacute;</em> as &ldquo;shore-men.&rdquo;) It is a composite language spoken along the East coast of Africa, dotted with Arabic loan words, and in fact once written in the Arabic script.&nbsp;</p>
<p>The great twelfth-century Persian mystical narrative by Shaikh &lsquo;A&#7789;&#7789;&acirc;r, entitled <em>Mantaq al-&#7789;ayr</em>, is a <em>safar</em>, kind of. It takes its title from Sulaym&acirc;n&rsquo;s knowledge of the <em>man&#7789;aq al-tayr</em>, the language of the birds. It is a voyage, but a paradoxical one, since the pilgrimage turns out to have been an illusion, or better an internal one. The birds assemble to discuss visiting the great authority figure among the birds, like Sulaym&acirc;n a S&icirc;n name, the Simorgh. They know about the Simorgh only that a single feather once fell on China. It enchanted every observer so powerfully that everyone recognized its importance. (The feather, Shaykh &lsquo;A&#7789;&#7789;&acirc;r adds, is now in a museum, a <em>neg&acirc;ristan</em>, in China.)</p>
<p>Shaykh &lsquo;A&#7789;&#7789;&acirc;r didn&rsquo;t invent the <em>s&icirc;morgh</em>. It goes way back. It had already appeared in secular form (supernatural but secular), a century and a half earlier, as the enormous bird in Ferdowsi&rsquo;s <em>Sh&acirc;hn&acirc;ma</em>, who protects Z&acirc;l and raises him as an adopted son. (Z&acirc;l is the son of the Persian S&acirc;m &ndash; not the one from the Old Testament.) I&rsquo;m told that one can trace the word <em>s&icirc;morgh</em> back through old Persian (it appears in the Avesta) to a Sanskrit term meaning eagle or falcon. &lsquo;Att&acirc;r creates a fanciful etymology,<em> s&icirc;</em> (thirty) <em>morgh</em> (birds) which makes the sound of its name as significant as its beauty.</p>
<p>The story <em>Man&#7789;aq al-tayr</em> becomes the account of a <em>safar</em>, kind of, but the greater part of the poem recounts the birds&rsquo; conversation, mostly parables, as the hudhud enlists them for the trip. There is a journey (across seven obstacles, <em>wadi</em>s, valleys, an itinerary since made proverbial in the theology of Bah&acirc;&rsquo;ism), but what readers remember is the terminal point, when only thirty (<em>s&icirc;</em>) birds are left and they discover that they are themselves the <strong>&#1587;&#1740; &#1605;&#1585;&#1594;</strong> s<em>&icirc; morgh</em>. The thirty birds. If Shayk &lsquo;A&#7789;&#7789;&acirc;r hadn&rsquo;t put it to such good use it would be a silly pun. In context it is a profound one.</p>
<p>We do not have to take it on faith that the <em>s&icirc;morgh</em> is beautiful. There is an illustration dating from the early 1500s, in the &ldquo;Houghton&rdquo; <em>Sh&acirc;hn&acirc;meh</em> (drawn in the 1520s, long after both the <em>Sh&acirc;hn&acirc;meh </em>and <em>Mantaq al-Tayr</em>, later given as a gift to the Ottoman sultan Selim the 2nd, another name from the S-L-M stem). I don&rsquo;t know whether that image of the <em>s&icirc;morgh</em> is one of the pages Houghton tore out and sold, but the images are easy to find (<a href="https://awalimofstormhold.wordpress.com/2011/03/13/the-simurgh/">for example</a>). The illustration shows the <em>s&icirc;morgh</em> (the one in Ferdowsi&rsquo;s account) in the upper left of the picture, claws planted on a vertiginous, multi-colored cliff, facing away from a party of horsemen down below, who are riding in from the right of the frame. The <em>s&icirc;morgh</em> is a little bigger than a horse, brandishing multi-colored tail feathers, looping streamers about twice as long as his body, fluttering toward the middle of the page. You could get lost in that tail. It unfolds in two tributaries, each with two parallel stripes of color, oddly not identical, one red (S&icirc;n word <em>sorkh</em>) and blue, one green (<em>sabz</em>) and brown. (Both pairs of color are separated by a thin strip of <em>sefid</em>, white.)</p>
<p>Four little knots of feathers at the base of the tail are in the same four colors, like a palette. If you look closely at those ribbons of color you see that the margins have a rough edge, little curled extensions that look as if they might be fractals. Behind them is a flat copper-colored sky. In the nest, with the albino Z&acirc;l, there is a miniature <em>s&icirc;morgh</em>, apparently happy to share a nest with a human adopted brother. The rocks and trees in the background are twisted in fanciful shapes that make them seem alive, but they would seem flat without those tail feathers in the foreground, which make the viewer feel the space between the background and our eyes, making visible the passing air, floating on a rightward breeze.</p>
<p>There are actually two pages showing the <em>s&icirc;morgh</em>. The other (<a href="https://upload.wikimedia.org/wikipedia/commons/7/79/Attributed_to_Abdul_Aziz_shahnama_1525_ZAL_IS_SIGHTED_BY_A_CARAVAN_Berlin%2C_Museum.jpg">for example</a>) shows the same scene, except that the simorgh is in flight, about to land, carrying an animal, perhaps a leopard, which is obviously dinner. Both pictures represent the <em>s&icirc;morgh</em> of the <em>Sh&acirc;hn&acirc;meh</em>, not the mystical <em>s&icirc;morgh</em> of Shaykh &lsquo;A&#7789;&#7789;&acirc;r. Still, both are beautiful enough to seem visionary and beyond understanding. To discover that you and twenty-nine friends are, collectively, identical with that being would be a satisfying experience. It would be worth the <em>safar</em>.</p>
<p>The Arabic word <em>simt</em>, plural<em> sum&ucirc;t</em>, means &ldquo;a direction.&rdquo; The <em>simt al-ra&rsquo;s</em>, the &ldquo;head&rdquo; i.e. the direction over the head, leads to the English word &ldquo;zenith.&rdquo; <em>Simt </em>is also used to describe the number of degrees which separate due north from a particular star. (It applies to points on other spheres, but the celestial context is the useful one.) English &ldquo;azimuth&rdquo; is from the same stem. <em>Simt</em> is a loan word into Arabic from Latin <em>semita</em>, a narrow path: it follows an etymological track which goes east and comes back again to Europe with a new, celestial identity. From <em>semita</em> to <em>sim&#7789;</em> and back to zenith. The practical use of the terms &ldquo;zenith&rdquo; and &ldquo;azimuth&rdquo; is in a boat, S&icirc;n word <em>saf&icirc;n </em>(or <em>saf&icirc;na</em>)</p>
<p><em>Al-Saf&icirc;na</em> is the constellation we know as Argo, or Argo Navis, whose brightest star is the one we call Canopus. In Arabic and Persian, Canopus is the S&icirc;n name Suhayl. There are other stars called Suhayl (Richard HinckleyAllen&rsquo;s <em>Star Names</em> lists eight. He adds that it became a general term for a bright star.) <em>Anw&acirc;r al-Suhayl&icirc;</em>, &ldquo;Lights of Canopus,&rdquo; or perhaps just &ldquo;Lights of a bright star,&rdquo; was the arbitrary title of a fifteenth-century work by Mulla Husain Bin &lsquo;Ali W&acirc;i'z-Al-K&acirc;shifi which retells the stories of <em>Kal&icirc;la wa Dimna</em> in Persian prose.</p>
<p>Suhayl is a star of the south. When the descendent of Timur, founder of the Mughal dynasty and diarist Babur first saw it, in 1504, while approaching Kabul from the north on his way to besiege it, it was important enough to note the event in his memoirs (<em>Baburnama</em>, 149). (The translator, Wheeler Thackston, estimates that it would have been three degrees above the horizon. The <em>sam&acirc;&rsquo;</em>, sky, must have been unusually clear.)&nbsp;</p>
<p>Suhayl occurs in a story, to me mysterious and incomplete, about the stars of Ursa Minor. Evidently the three stars we see as the handle of the dipper, the <em>Ban&acirc;t al-na&lsquo;sh</em>, are the daughters of whoever is lying in the rectangle, the <em>na&lsquo;sh</em> &ndash; dead body or coffin. (Or is Na&lsquo;sh a proper name?) But you also hear that the corpse in the rectangle was killed by the Pole Star, in which case there are only two mourners in the procession. Richard Hinckley Allen (in <em>Star Names</em>), says that they are waiting for Suhayl to come from the south and help them. Good luck.</p>
<p>S&icirc;n character Sindb&acirc;d, anglicized as Sinbad, is like Solomon a household word in English, whose voyages (like those of the birds) add up to seven &mdash;&nbsp;<em>sab&lsquo;</em>. He begins as a merchant, traveling from <em>s&ucirc;q</em> to <em>s&ucirc;q</em><strong>, </strong>who keeps getting sidetracked. The first of the voyages is the most famous, the one that centers on S&icirc;n word <em>samaka</em>, a fish. The captain spots his island, lowers the anchor and their boat begins to sink into the ocean because (as the captain realizes a bit too late) it isn&rsquo;t an island at all, just an enormous fish which has floated motionless for a while, a great while, long enough to gather a layer of topsail and grow trees. (The fish is so big that it is mistaken for a land mass, an error of classification you often find in folklore.) When the mega-whale wakes up, it generates a whole other story by leaving the crew of Sindbad&rsquo;s boat bobbing in the water. (Sinbad ends up grabbing a wooden tub and floating his way towards the next event.)&nbsp;</p>
<p>Probably the most famous S&icirc;n word associated with the <em>1001 Nights</em> comes from the story &ldquo;Ali Baba and the Forty Thieves.&rdquo; It is not strictly speaking part of the <em>Nights</em>, though it is a story of the same genre and doesn&rsquo;t feel out of place. (It was added by Antoine Galland in 1704, in his French translation of stories from the<em> Nights</em>.) It&rsquo;s the magic charm that Ali Baba uses to open the door to the buried treasure: &ldquo;open Sesame.&rdquo; <strong>&#1575;&#1601;&#1578;&#1575;&#1581; &#1740;&#1575; &#1587;&#1605;&#1587;&#1605;</strong> &ldquo;Ift&acirc;&#7717; y&acirc; Simsim.&rdquo; If we don&rsquo;t know it from Ali Baba we know it from &ldquo;Sesame Street.&rdquo; And if we don&rsquo;t know &lsquo;Ali Baba as he is alluded to on Sesame Street, we are likely to know the name from the Chinese company Ali Baba, Jack Ma&rsquo;s equivalent of Amazon.</p>
<p>&ldquo;Ift&acirc;&#7717; y&acirc; Simsim&rdquo; is an imperative. When a subordinate hears a command in the <em>Nights</em>, you are likely to hear, in English translations, the (also familiar) reply: &ldquo;To hear is to obey...&rdquo; It&rsquo;s a pretty accurate word-by-word translation of S&icirc;n response <strong>&#1587;&#1605;&#1575;&#1593; &#1608; &#1591;&#1575;&#1593;&#1577;</strong><em> sam&acirc;&lsquo; wa &#7789;&acirc;&lsquo;a</em> -- the verbal nouns for hearing and obeying. (To hear is to obey. The Richard Burton translation, for some reason, says &ldquo;hearkening and obedience.&rdquo;)</p>
<p class="illo"><img src="../_img/sin-07.png" width="650" /></p>
<h3>Fellow Readers</h3>
<p>Once you get caught up in the <em>Nights</em> you may get caught up in the commentary as well, if only because fans and enthusiasts like company. Lately (after generations of being thought sub-literary) the <em>Nights</em> have become increasingly popular for historians, literary critics, theorists and philologists. <em>The Nights</em> allow a student to study the history and ancestry of surviving manuscripts. The physical chain is like a bottomless container. It might as well be infinite. One of the earliest fragments (an early example of a manuscript on paper rather than parchment), dating from the 9th century, now at the Oriental Institute at the University of Chicago (#17618), is part of a page containing five short lines from the opening pages of The Nights, scattered fragments of the text in different hands, the outline of the figure of a man, the rough draft of a letter from someone in Antioch, and the opening phrases of a legal document dated 266 / 879 CE. I get this from a masterful study of the manuscript by Nabia Abbott in Ulrich Marzolph&rsquo;s <em>Arabian Nights Reader</em> ([2006], 21-82). The story of that single multi-purpose page is like a novel, except that as a novel it would be improbable, self-conscious and pretentious. As a historical reality, the physical object holding the text is place, it is novelistic and beautiful.</p>
<p>Then there are the stories themselves, and the architectural logic that holds the narrative building blocks together, the styles and story types, the themes and cultural values. It&rsquo;s a book that has found its moment in history. One appeal may be that it is amorphous, fluid (<em>s&acirc;&rsquo;il</em>), like a cloud (a<em> sa&#7717;&acirc;ba</em>). Then there is the charm of a complex work without a known author to get in the way. And then, since it has been taken seriously only in recent times, there is the pleasure of showing our solidarity with a work outside the official acceptable classics, a way to say we are with the people rather than the pedants and their damned canon.</p>
<p>If they were oral stories they would be further outside the canonic limits, but they are clearly literate creations which took their shape on paper, the sum of variations handed down from one scribal improviser to another. We know it&rsquo;s pieced together from various sources, with no consistent style, no consistent menu of stories and with no particular reason to judge one version over another. If they were at one time oral stories, those spoken versions are historically speaking way upstream from the stories we have. There is no particular elegance of style to force a close-up verbal analysis. The stories may seem stripped down, stories in their pure state, a non-alphabetized encyclopedia of narrative types. Then there is the math.</p>
<p>The shape of <em>The nights </em>of storytelling add up for no natural reason to the meaningful 1001 nights. One obvious answer is that 1000 represents plenitude; add one and you&rsquo;re at plenitude and beyond. Another interpretation, not canonical, observes that if seven, the number of good luck, thirteen, the number of bad luck, and eleven (called, for some reason &ldquo;the fool&rsquo;s number&rdquo; &ndash; perhaps something to do with the lore of Tarot cards?), are multiplied, they come to 1001. 13 x 7 x 11.</p>
<p><em>Us&#7789;&ucirc;ra</em> (pl. <em>as&acirc;&#7789;&icirc;r</em>) is the term for a myth or fable. It is said to be a loan word from Greek <em>histor&iacute;a</em>, which has a privileged ancestry in the western languages. On the other hand, it does fit into an indigenous Arabic stem: S-&#7788;-R means to write, with an emphasis on the physical sense of writing, in rows on a writing surface. Perhaps because straight lines across a sheet paper are divisions, the same stem gives us <em>s&acirc;&#7789;&ucirc;r</em>, a cleaver. The stories of the Nights are written, <em>mast&ucirc;r</em>, rather than spoken or recited. This makes easy a formulaic break when the story pauses to wait for the next night. When Shahrazad sees the dawn there is <em>sakta</em>, silence (<em>Sakatat &lsquo;an al-kal&acirc;m al-mub&acirc;&#7717;</em>, &ldquo;She fell silent from the words that had been allowed to her.&rdquo;) We don&rsquo;t learn what happened in daylight between stories. For readers, the interruptions of the story are just striations on the surface of the text. We don&rsquo;t have to wait at all: we can just keep reading and forget the next day. It doesn&rsquo;t occur on the page at all. But for the king they are day-long interruptions. We have more freedom than he has.</p>
<p>S&icirc;n word <em>si&#7717;r</em> means magic. The Nights are full of <em>si&#7717;r</em>. You can find magic inside the stories, with spells and transformations, levitations, monsters and shifting shapes which surprise the character who encounters them. Sometimes what looks like <em>si&#7717;r </em>is actually science, as when the physician Dub&acirc;n keeps his decapitated head alive and talking from its perch on a plate filled with a medicine he has prepared in advance. It comes across as magic, but it is simply because he knows the right chemicals. Sometimes <em>si&#7717;r</em> lurks silently behind the surface of the story, neither named nor acknowledged, an invisible shaping force lurking underneath the coincidences and unexplained turns of fortune, as a magnet hidden beneath a sheet of paper shapes the iron filings. It is the magic acting outside the story, the sense of a charmed world, more familiar to us than to the characters. When Qamar al-Zam&acirc;n falls in love with Bud&ucirc;r but knows neither her name nor her location, we know fate will bring them together. When Ma&lsquo;r&ucirc;f the Cobbler is magically transported from Cairo to the (fictional) city of Ikhtiy&acirc;n al-Khatan, we can be pretty sure that we are caught up in a network of story-telling that will arrange for him to marry the princess.</p>
<p>And then there is the heroism. The frame story in which a wife humanizes a deranged king by telling tales, saving her own life, as well as the lives of women throughout her community, by means of fabulation, is a meta-tale of cunning and courage. The story-teller as risk-taker. Whether or not storytelling is characteristic of women, or whether the stories of the Nights tend to express a woman&rsquo;s point of view (or whether the generations of copyists were women or men), Shahrazad&rsquo;s bravery is a monument of world literature. In most examples of bravery in stories, where we are told the hero is brave or resourceful, it&rsquo;s an assertion without evidence. In Shahrazad&rsquo;s case, the stories demonstrate it. We see her bravery in the form of stories laid out in front of us. No tricks. It would have been possible to say &ldquo;and then she told stories for many nights,&rdquo; but we get to read the actual stories. We see them on the page. As a math teacher might say, the story shows her work. The stories are often suspenseful even for a wary, jaded modern reader, but for the fictional listener, the serial killer king Shahryar, they are more suspenseful still (since he has to wait a day after every installment.) They would be suspenseful for the storyteller as well. And yet of course, down deep, readers know things will end happily. That happy ending is a kind of <em>si&#7717;r </em>whether something supernatural happens or not.</p>
<h3>Happy</h3>
<p>Although, for us, the stories of the <em>Nights</em> are there simply to amuse, utterly without politics, in the individual stories they always have a function &ndash; to make a point in an argument, to avoid punishment, to threaten, to keep the story-teller alive. Often they are answers to a <strong>&#1587;&#1572;&#1575;&#1604;</strong> &ndash; a <em>su&rsquo;&acirc;l,</em> a question, like the king&rsquo;s unspoken &ldquo;What happens next?&rdquo;</p>
<p>There is also in Arabic literature a tradition of questions that receive no answers. In the opening scene of the pre-Islamic <em>qaṣ&icirc;da</em>, the traditional visit of the poet to a plot of ground where a loved woman&rsquo;s tribe once camped, among the many things generically patterned to happen (time has intervened, he reads the signs the tribe has been there, he remembers their encounters) is an incomplete dialogue. When he interrogates the encampment, the result is silence. The late Jaroslav Stetkevych, in a beautiful essay I cite regularly, &ldquo;Toward an Arabic Elegiac Lexicon,&rdquo; lists seven (<em>sab&lsquo;a</em>) key words that characterize the <em>qaṣ&icirc;da </em>genre. Seventh in the list is <em>su&rsquo;&acirc;l</em>. For example, there is the opening of a poem by the pre-Islamic poet Al-N&acirc;bigha Al-Dhubyan&icirc;. He stops at the scene of the encampment: &ldquo;I halted at the abode&rsquo;s springtime grounds, / its semblance altered by decay,&rdquo; and then</p>
<blockquote>
<p><strong><em>Us&acirc;&rsquo;ilu</em></strong><em> &lsquo;an Su&lsquo;d&acirc; wa qad marra ba&lsquo;dan&acirc;<br /></em><em>&lsquo;al&acirc; &lsquo;araṣ&acirc;ti al-d&acirc;ri sab&lsquo;un kaw&acirc;mil&ucirc;</em></p>
<p>[ . . . asking questions about Su&lsquo;d&acirc; while, after us,/seven years had passed over the abode&rsquo;s yards (&ldquo;Lexicon,&rdquo; 106-07).]&nbsp;<br />It&rsquo;s been seven years since she was there. There won&rsquo;t be an answer. It is probably meaningful that her name is<em> Su&lsquo;d&acirc;&rsquo;</em>, &ldquo;Happy.&rdquo;</p>
</blockquote>
<p>Each evening Shahrazad begins&ldquo;it has reached me, O happy king. . .&rdquo; <em>ayuyh&acirc;</em> al <em>malik al-sa&lsquo;&icirc;d</em> . . . Sa&lsquo;&icirc;d derives from the word for happiness, luck, good fortune, S&icirc;n word, <em>sa&lsquo;d</em> (from the stem S- &lsquo;- D). Thus S&acirc;&lsquo;id, Su&lsquo;&acirc;d, Mas&lsquo;oud, Su&lsquo;d&acirc;&rsquo; The first name of the great Syrian playwright Sa&lsquo;dallah Wannus and the family name of theTunisian poet and visionary Mahm&ucirc;d Mas&lsquo;ad&icirc; are derived from the same origin. Sa&lsquo;d&icirc;, &ldquo;the happy one,&rdquo; is the pen name of the great Persian poet. The &ldquo;saudi&rdquo; of Saudi Arabia, <em>Al-malika al-&lsquo;Arabiyyya al-su&lsquo;&ucirc;ddiyya i</em>s from the same stem. The inhabitants of upper Egypt are called Sa&lsquo;&icirc;d&icirc;s, the implication being that nothing bothers them. Arabia Felix is the now tragically inappropriate Latin name for Yemen, <em>Al-Yaman al-Sa&lsquo;&icirc;d</em>.</p>

<p class="illo"><img src="../_img/sin-03a.png" width="400" /></p>


	
</article>
<cfinclude template="../_footer.cfm">

